### ISSUE TITLE
(bug) Fetching variant details returns an internal type

### ISSUE THREAD

**Issue by lydamian** [thomaspoignant/go-feature-flag#1031]
### Observed behavior

Any of the variantDetail functions e.g [StringVariationDetails](https://pkg.go.dev/github.com/thomaspoignant/go-feature-flag#StringVariationDetails) returns an internal type https://pkg.go.dev/github.com/thomaspoignant/go-feature-flag@v1.15.0/internal/model#VariationResult
see
<img width="1038" alt="Screenshot 2023-08-26 at 5 37 34 PM" src="https://github.com/thomaspoignant/go-feature-flag/assets/33501312/35fd13e4-5d0a-4eb4-b3ee-41035558ffbe">

This causes problems because we cannot import this type for typing vars
we get this error "could not import github.com/thomaspoignant/go-feature-flag/internal/model (invalid use of internal package "github.com/thomaspoignant/go-feature-flag/internal/model")"

### Expected Behavior

Make the type here https://pkg.go.dev/github.com/thomaspoignant/go-feature-flag@v1.15.0/internal/model#VariationResult publicly accessible (not in the internal folder)

### Steps to reproduce

Create a new go application

go get github.com/thomaspoignant/go-feature-flag

```
package main

import (
	"fmt"
	"time"

	ffclient "github.com/thomaspoignant/go-feature-flag"
	"github.com/thomaspoignant/go-feature-flag/ffcontext"
	"github.com/thomaspoignant/go-feature-flag/internal/model"
	"github.com/thomaspoignant/go-feature-flag/retriever/fileretriever"
)

// this is a perfectly valid usecase but it doesn't work becuase we cant import github.com/thomaspoignant/go-feature-flag/internal/model
func getVariantDetails(userKey string) (model.VariationResult[string], error) {
	user := ffcontext.NewEvaluationContext(userKey)
	return ffclient.StringVariationDetails("your.feature.key", user, "control")
}

func main() {
	err := ffclient.Init(ffclient.Config{
		PollingInterval: 3 * time.Second,
		Retriever: &fileretriever.Retriever{
			Path: "flag-config.yaml",
		},
	})
	defer ffclient.Close()

	// Call the getVariantDetails function and print the result
	variantDetails, err := getVariantDetails("user1-key")
	if err != nil {
		fmt.Printf("Error: %v\n", err)
		return
	}

	fmt.Printf("Variant details: %v\n", variantDetails)
}

}
```

**Comment by thomaspoignant** [comment]
Hey @lydamian thanks a lot for this issue, you are totally right there is something we need to change here.

I am currently in vacation and will not be able to work on this before next week, but I will look at it when I am back.
If you want you can also open a PR for this and I will review it as soon as I have access to my computer.

**Comment by thomaspoignant** [comment]
@lydamian a fix is on his way and will be available in the next version.
You can check the associated PR #1047

**Comment by lydamian** [comment]
Awesome! Thanks will take a look

**Comment by thomaspoignant** [comment]
@lydamian the version `v1.15.1` has been released and you will be able to use the struct now.
