### ISSUE TITLE
(feature) Add a GCP pubsub data exporter

### ISSUE THREAD

**Issue by thomaspoignant** [thomaspoignant/go-feature-flag#1128]
### Requirements

Add a pubsub data exporter, the example of the SQS exporter could be a great introduction about the topic.
https://github.com/thomaspoignant/go-feature-flag/tree/main/exporter/sqsexporter

**Comment by sham-nt** [comment]
Hey can I contribute to this?

**Comment by thomaspoignant** [comment]
> Hey can I contribute to this?

Sure this is all yours if you want to try.
I’ll affect you the issue.

**Comment by sham-nt** [comment]
hey, I cloned the repo and started working, but I think this is a bit too complex for my skill level. So to avoid pushing bad code, I will unassign myself

**Comment by thomaspoignant** [comment]
@sham-nt I can help you if you want.
It should be pretty straightforward. Feel free to come on [slack](https://gophers.slack.com/messages/go-feature-flag) and I can give you some advice.

**Comment by JigarJoshi04** [comment]
@thomaspoignant I can work on this.
Please assign this to me.
I will start contributing to this

**Comment by thomaspoignant** [comment]
@JigarJoshi04 awesome if you want to work on it.
I have assigned it to you.

**Comment by JigarJoshi04** [comment]
Also please add me to the slack community.
Because I am not able to join the slack community.
My email: jigar.04.joshi@gmail.com // jigar.pj@somaiya.edu

Thanks

**Comment by lothar1998** [comment]
Hi, I would be interested in this one
/assign-me

**Comment by thomaspoignant** [comment]
> Hi, I would be interested in this one /assign-me

Hey awesome, let me know if you need any help on this.
If you prefer to slack, you can join the #go-feature-flag slack channel following those [instructions](https://gofeatureflag.org/slack).
