### ISSUE TITLE
(feature) Allow force-refreshing or invalidating the cache

### ISSUE THREAD

**Issue by ianlyons** [thomaspoignant/go-feature-flag#1130]
### Requirements

Hi! I've loved using the library and really appreciate what you've done.

I'd love to be able to invalidate the cache after updating a flag value so that I don't need to wait until `PollingInterval` elapses to see the flag value update.

I'm happy to contribute the change, but first want to make sure that it aligns with your view of the project and that I'm not "holding it wrong".

(It's totally possible that I missed this existing functionality as well! If so, could you point me in the right direction?)

Again, many thanks!

**Comment by thomaspoignant** [comment]
Hey @ianlyons thanks for the kind words, I am glad you like GO Feature Flag.

I am curious to understand why you want to invalidate the cache, and what will be the trigger to ask for the invalidation.
Do you want to explicitly call a function from your code to ask the lib to call again the retrievers? 
If yes when will you call this function?

**Comment by thomaspoignant** [comment]
I am closing this issue due to the lack of an answer.
Feel free to reopen it if you want more information.
