### ISSUE TITLE
(bug) invalid retriever: no "URL" property found for kind "gitlab"

### ISSUE THREAD

**Issue by CMiksche** [thomaspoignant/go-feature-flag#1242]
### Observed behavior

I wanted to setup the `go-feature-flag-relay-proxy` with the `gitlab` retriever.

For the configuration I followed the documentation at https://gofeatureflag.org/docs/relay_proxy/configure_relay_proxy#retriever. (This documentation needs rework btw, the whole section describing the GitLab Token is just copied from the GitHub description without a change of name)

Either the configuration or the code has a bug because the following error comes after setting up a config file like this (I changed the variables to anonymise my data):

**Config file:**

```
listen: 3001
fileFormat: yaml
enableSwagger: true
startWithRetrieverError: false
retriever:
  kind: gitlab
  repositorySlug: org/repo
  path: config.goff.yaml
```

**Error:**

`{"level":"fatal","ts":1699751215.054761,"caller":"relayproxy/main.go:60","msg":"configuration error","error":"invalid retriever: no \"URL\" property found for kind \"gitlab\"","stacktrace":"main.main\n\t/home/runner/work/go-feature-flag/go-feature-flag/cmd/relayproxy/main.go:60\nruntime.main\n\t/opt/hostedtoolcache/go/1.21.3/x64/src/runtime/proc.go:267"}`

After adding a `URL` property to the config (btw, on the webpage this is called `baseUrl`), this error is solved and another occurs:

```
panic: impossible to retrieve the flags, please check your configuration: request to https://gitlab.com/api/v4/projects/org%252Frepo/repository/files/config.goff.yaml?ref=main failed with code 403

goroutine 1 [running]:
main.main()
	/home/runner/work/go-feature-flag/go-feature-flag/cmd/relayproxy/main.go:85 +0xc75
```

Here the `%252F` seems to mean that the `/` is double encoded which obviously results into a failing API request.

### Expected Behavior

1. The documentation should use `GitLab` in the description for the GitLab Token, not `GitHub`
2. There should be no error `invalid retriever: no "URL" property found for kind "gitlab"` because I use the default URL of GitLab and it than shouldn't expect any property
3. It shouldn't search for any `URL` property because the documentation says this property is called `baseUrl`
4. The API request to GitLab shouldn't double encode the backslash in the slug

### Steps to reproduce

I use the current version v1.18.0

**Comment by thomaspoignant** [comment]
Hey @CMiksche thanks for this details issue.
I'll have a look at it and I will fix the Gitlab related issue.

**Comment by thomaspoignant** [comment]
@CMiksche I will release a version `v1.18.1` Today that fixes the issues and the documentation.
