### ISSUE TITLE
(feature) Add ability for proxy to inject context

### ISSUE THREAD

**Issue by richardj-bsquare** [thomaspoignant/go-feature-flag#1270]
### Requirements

I'd like to be able to add additional context at the proxy level that can be used in addition to the context provided by the client through the proxy.

For example, the user requests a feature flag passing in email address. The proxy adds additional context that was configured by it, such as the environment in which the proxy is run, such as 'production: true/false'. These two values are then used by the rules to return the desired flag. 

The use cases are wide-ranging, but essentially consist of context that a generic service or client using the proxy does not know or need to know, but affects the rule processing. This tends to be very necessary when you have multiple deployed environments, where there is a set of dev, staging or production environments and you want differing behaviour between them but don't want to pollute services with environment-specific context.

It may be that this feature exists, but I was unable to find a way to do this.

I had a quick look at the proxy code, and it seems that additional configuration in the form of a context section would be required and then the values in there would be merged with with the incoming client context (probably with the proxy context taking precedence for any matching keys), before passing down to the go-feature module itself.

**Comment by thomaspoignant** [comment]
Hello @richardj-bsquare I like this idea and it will be a nice addition to what is already available.

**Comment by thomaspoignant** [comment]
@richardj-bsquare I have opened a pull request for this new feature.
If you can have a look at it and give me some feedback, I would like to see if it can solve what you had in mind.

https://github.com/thomaspoignant/go-feature-flag/pull/1285
