### ISSUE TITLE
(change) Request to rename the folder name inside the exporter folder

### ISSUE THREAD

**Issue by JigarJoshi04** [thomaspoignant/go-feature-flag#1292]
### Motivation

The different subfolders in the exporter folder ends with exporter keyword.
It is really not necessary to have that keyword as it is understood that we are already in the exporter folder.

### Requirements

Renaming of the folders and maybe packages

**Comment by thomaspoignant** [comment]
Hello @JigarJoshi04 I understand why you want to rename all the exporters, but if we change the folder names it will be a breaking change for all people using those exporters.

I don't think this breaking change is worth it.
However, I am not opposed to creating new exporters without the exporter name in it.
