### ISSUE TITLE
(feature) Offline mode

### ISSUE THREAD

**Issue by thomaspoignant** [thomaspoignant/go-feature-flag#131]
# Requirements
In some situations, you might want to stop making remote calls and fall back to default values for your feature flags. For example, if your software is both cloud-hosted and distributed to customers to run on premise, it might make sense to fall back to defaults when running on premise. You can do this by setting Offline mode in the client's Config.

Add an `Offline` field in the config to disable remote calls.

**Comment by GoGstickGo** [comment]
@thomaspoignant , Would you mind describe a more specific use case ?  Is this feature relates to retriever as reading the flag file only locally?

**Comment by thomaspoignant** [comment]
The goal of this new option is to be sure that we are not trying to retrieve the config file and to always serve the default value (passed in the variation).
