### ISSUE TITLE
(Go feature flag + Offline mode) <offline mode>

### ISSUE THREAD

**Issue by to-long** [thomaspoignant/go-feature-flag#1332]
### Requirements

Other providers of Open features provide Offline Mode. 
How is `go feature flag offline mode` ? 
I tried to find but not found, please give me the url or sample

**Comment by thomaspoignant** [comment]
Hello @to-long,
What do you mean by offline mode? 
I am not sure to fully understand what you call that way.

**Comment by to-long** [comment]
hi @thomaspoignant , I just want to download remote config from S3 and don't want to use relay proxy. How can I do it ?

**Comment by thomaspoignant** [comment]
if you are using OpenFeature you will need the relay proxy.
I think I understand what you want, is it to have an in-process evaluation of your flag?

If that's the case, for now only the `go` provider is supporting in-process evaluation.
