### ISSUE TITLE
Why we cannot implement custom Retrievers?

### ISSUE THREAD

**Issue by maxifom** [thomaspoignant/go-feature-flag#135]
As I can see Retriever has got private method, so it cannot be implemented and there is no way the library can be extended. Is there any particular reason why so?

**Comment by thomaspoignant** [comment]
@maxifom I have this in the back of my mind for a few weeks, I think it would be preferable to let this possibility, you are right.

The only tradeoff I see is that people will start building their custom retrievers without contributing into the project.

**Comment by maxifom** [comment]
> @maxifom I have this in the back of my mind for a few weeks, I think it would be preferable to let this possibility, you are right.
> 
> 
> 
> The only tradeoff I see is that people will start building their custom retrievers without contributing into the project.

I see a use case in some custom retrieve login, you cannot write adapters for every possible use case, and if some people want to write some, they will probably not open source for their specific use case, and I hope most of the people that do, won't just push it without collaboration with this repo, it would be inappropriate I guess
