### ISSUE TITLE
(feature) Create a mongodb retriever

### ISSUE THREAD

**Issue by thomaspoignant** [thomaspoignant/go-feature-flag#1370]
## Requirements

GO Feature Flag was initially built to load the flag configurations from a file for simplicity.
But since we already cover a large portion of destinations to store the file, we've seen some needs to do it in a database as well for a bigger system.
MongoDB is a good candidate to store the flags.

For this we will need to implement a new [retriever](https://gofeatureflag.org/docs/configure_flag/store_your_flags) that will connect to mongoDB read all the available flags in a collection and marshal _(`yaml`, `toml` or `json` depending on parameters [format](https://github.com/thomaspoignant/go-feature-flag/blob/f183e9b286b77b0c191a5c64c6cfd1045d1965e0/config.go#L57))_ the result to send it as `[]bytes`.

- [ ] Create a MongoDB retriever in the [`/retriever`](https://github.com/thomaspoignant/go-feature-flag/tree/main/retriever) folder
- [ ] The retriever should implement the interface [`retriever`](https://github.com/thomaspoignant/go-feature-flag/blob/main/retriever/retriever.go)
- [ ] It should be possible to use the retriever in the relay-proxy (support configuration in [`cmd/relayproxy/config/retriever.go`](https://github.com/thomaspoignant/go-feature-flag/blob/main/cmd/relayproxy/config/retriever.go))
- [ ] Add documentation for this retriever.

**Comment by luizgribeiro** [comment]
Hey @thomaspoignant!

I have a few questions on this.
1. I'm thinking about an API for the retriever that uses the mongoURI, db name and collection name. Should the connection be created and it's end deferred in the retriever or a long lived connection be used?
2. Should we validate the documents returned from the DB in order to make sure that each one has the correct structure? I'm thinking about discarding those that are invalid. What do you think?
3. What would you say that are good test approaches for this? Should integration tests be set up with a mongodb container?

**Comment by thomaspoignant** [comment]
Hey @luizgribeiro super happy to see you working on this one.
Let me try to answer your questions:

1. I think this is the right approach, when it comes to the management of the connection I will be in favour of using a long-lived connection since the retriever is not closed and stays alive.
2. There is no need to validate, there is a validation when we get the value from the retriever that is common to all retrievers.
    To understand how the retriever system works it follow those steps:

    - GOFF is calling the retriever
    - The retriever gets the flags and returns them as a `yaml` / `json` / `toml` representation in `[]bytes`. 
    - After that, GOFF will unmarshal the file format into a `struct`.
    - And before adding them to the in-memory cache it will validate the format (see [here](https://github.com/thomaspoignant/go-feature-flag/blob/13cb98475579bbf21d73e2704f29a87980795736/internal/cache/in_memory_cache.go#L70)).

    So if for any reason how it is stored in Mongo is wrong, I see 2 moments where it can fail, when unmarshalling or when validating, and both of them are good enough in my opinion.

3. Good question 🤔, for other retrievers the test approach was always to mock the remote system, but since here we are talking about something that can run inside a container, I am fine with both approaches and I even think that it could probably be easier to have it running as an integration test. I suggest that you take your favorite approach here.

**Comment by luizgribeiro** [comment]
Alright.

One more thing, what is the expected model/schema of the db in this case?
If we're talking about multiple documents we'll need a field being mapped to flag key (and we'll need transform de document before passing the []byte).
Something like this:
```js
[
  {
     flag: "test-flag",
     variations: ...
  },
  {
    flag: "another-flag",
    variations: ...
  }
]
```

Another option (which I don't like) is using one single document with all flag declarations like this:
```js
{
  "test-flag": {
      variations: ...
  },
  
  "another-flag": {
      variations: ...
  }
}
```

**Comment by thomaspoignant** [comment]
What makes more sense to me is your first option.
I haven't thought about the schema yet, but it will be super close to the JSON representation of a flag.
