### ISSUE TITLE
(feature) Create a redis retriever

### ISSUE THREAD

**Issue by thomaspoignant** [thomaspoignant/go-feature-flag#1371]
## Requirements

GO Feature Flag was initially built to load the flag configurations from a file for simplicity.
But since we already cover a large portion of destinations to store the file, we've seen some needs to do it in a database as well for a bigger system.
Redis is a good candidate to store the flags.

For this we will need to implement a new [retriever](https://gofeatureflag.org/docs/configure_flag/store_your_flags) that will connect to redis read all the available flags and marshal _(`yaml`, `toml` or `json` depending on parameters [format](https://github.com/thomaspoignant/go-feature-flag/blob/f183e9b286b77b0c191a5c64c6cfd1045d1965e0/config.go#L57))_ the result to send it as `[]bytes`.

- [x] Create a Redis retriever in the [`/retriever`](https://github.com/thomaspoignant/go-feature-flag/tree/main/retriever) folder
- [x] The retriever should implement the interface [`retriever`](https://github.com/thomaspoignant/go-feature-flag/blob/main/retriever/retriever.go)
- [x] It should be possible to use the retriever in the relay-proxy (support configuration in [`cmd/relayproxy/config/retriever.go`](https://github.com/thomaspoignant/go-feature-flag/blob/main/cmd/relayproxy/config/retriever.go))
- [x] Add documentation for this retriever.

**Comment by lucionathan** [comment]
Hey @thomaspoignant !!!

I have some questions:

1. Do you think the right approach to the redis retriever would be to connect the redis via url? [https://github.com/redis/go-redis#connecting-via-a-redis-url](https://github.com/redis/go-redis#connecting-via-a-redis-url)
2. Is there a Discord or similar channel where I can ask questions about the project?

Thanks in advance!

**Comment by thomaspoignant** [comment]
Hello @lucionathan, thanks for taking care of this issue.
Let me try to answer your questions:

1. I am not a huge expert on the Redis integration with Golang, but I think the client approach seems to be a bit better and will be maybe more explicit in terms of the configuration of the retriever _(specifying only the field needed for the client etc ...)_.
2. Yes you can join the `#go-feature-flag` channel on the gopher slack, to do this please follow the instruction on this page https://gofeatureflag.org/slack

**Comment by lucionathan** [comment]
Hey @thomaspoignant!

I have some questions again:

1. If the user uses redis to store their config files, is it expected to the file to be stored as bytes directly or as a string? Or doesn't concern me how the file is stored?
2. Would you recommend using docker or mock in the tests? I thought that with docker the tests would be more trustworthy because I would test the application using redis directly, and not a mock of the redis.
3. If docker is a pick here, how would you recommend me to structure the tests? Like, where should I initialize the docker? I'm having a problem with that!
4. If the mock is the option, I saw that go-redis has a mock package (https://github.com/go-redis/redismock), but I failed to understand how it could be used to test, could you help me with that?

Thanks in advance! And sorry if I missed something simple!

**Comment by thomaspoignant** [comment]
Hi @lucionathan,
sorry for the delay to answer you, let me try to answer your questions:

1. How I saw this was to have an entry per flag, with the name of the flag as a key and we can store the value in `JSON` using the [`JSON` type](https://redis.io/docs/data-types/json/) of Redis.
2. For other retrievers the test approach was always to mock the remote system, but since here we are talking about something that can run inside a container, I am fine with both approaches and I even think that it could probably be easier to have it running as an integration test. I suggest that you take your favourite approach here.
3. We have no test today using docker for now, I can work on preparing an environment to start and stop the docker in the test, but this is not ready yet.
To unblock you, you can do your test with docker ready and I'll try to bring the capability in the code base in the meantime.
4. I am happy to help you with `redismock` even if I have never used it, ping me on slack and we can try it together.
