### ISSUE TITLE
(feature) editor - Create a better rule editor

### ISSUE THREAD

**Issue by thomaspoignant** [thomaspoignant/go-feature-flag#1372]
## Requirements

In the flag editor _(https://editor.gofeatureflag.org)_ creating a rule is a simple textarea.
It would be great to have a more advanced rule editor supporting making it easy the creation of a complex rule.

Supported case are the following https://gofeatureflag.org/docs/configure_flag/rule_format#query-format

One idea would be to have something like this:
![Image](https://github.com/thomaspoignant/go-feature-flag/assets/17908063/d49a904c-026a-4493-a5f0-2b220ba50fcb)

But I am happy to challenge this if someone has a better idea on how to have a great UX for that.

The source of the editor are available https://github.com/thomaspoignant/go-feature-flag/tree/main/website/src/pages/editor

**Comment by Esequiel378** [comment]
@thomaspoignant I've started working on this feature! I will be creating the PR soon 🤗

**Comment by thomaspoignant** [comment]
@Esequiel378 awesome ! I’ll affect you the issue.
