### ISSUE TITLE
Documentation: Native english speaker validation

### ISSUE THREAD

**Issue by thomaspoignant** [thomaspoignant/go-feature-flag#1524]
## Requirement

As a main contributor to GO Feature Flag, I am also the main contributor to the documentation website https://docs.gofeatureflag.org.

Since I am not a native English speaker _(sorry I am 🇫🇷)_, the English level is not perfect and may be improved.
I am looking for contributors ready to help the documentation to reach the next level.

The source of the documentation is available at https://github.com/thomaspoignant/go-feature-flag/tree/main/website/docs.

**Comment by D5D0Ds** [comment]
I would be happy to help with this.

**Comment by thomaspoignant** [comment]
Oh awesome, feel free to write a message with `/assign-me` in this issue to affect it to you.

**Comment by D5D0Ds** [comment]
I hope I haven't overdone it. Please provide your feedback. I am open to working on it.
