### ISSUE TITLE
(bug) ffclient.Init throws an error on an invalid file during compiled run but not on test (golang)

### ISSUE THREAD

**Issue by MRyanPW** [thomaspoignant/go-feature-flag#1576]
### Observed behaviour

I'm trying to write a test for loading in a invalid flags config file (json, if that matters, though it seems to happen with any other type), but for some reason the function responsible for calling ffclient.Init isn't throwing an error like expected. However, when compiling the golang app and calling the same function with the same file, it _does_ throw the expected error.

### Expected Behavior

When calling the init function using a setup similar to https://gofeatureflag.org/docs/go_module/store_file/file the function doesn't throw an error when provided an invalid file. It doesn't seem to matter if the entire path is provided or not, or even if the file is actually an invalid config file or not. ffclient.Init doesn't throw an error and doesn't appear to be evaluating the data from the retriever.

I've gone so far as to copy the fileretriever.Retriever setup and paste into my code with a bunch of logging, but it doesn't appear that is ever hit in the testing process. The only time I was able to get it to call was manually calling ffclient.New with the config and that hit, but not the ffclient.Init that was literally immediately after. 

### Steps to reproduce

```golang
func initFeatureFlags(flags_file string) error {
	if flags_file == "" {
		return errors.New("Invalid feature flags file")
	}
	
	err := ffclient.Init(ffclient.Config{
		PollingInterval: 3 * time.Second,
		Retriever: &fileretriever.Retriever{
			Path: flags_file,
		},
	})
	if err != nil {
		return fmt.Errorf("Error initializing feature flags: %v", err)
	}
	
	return nil
}

func Test_initFeatureFlags(t *testing.T) {
	t.Run("fail if json file doesn't exist", func(t *testing.T) {
		err := initFeatureFlags("THIS_WONT_WORK")
		
		assert.NotNil(t, err)
		assert.Contains(t, err.Error(), "Error initializing feature flags:")
	})

	t.Run("fail if json file is empty", func(t *testing.T) {
		err := initFeatureFlags("fail_empty.json")
		
		assert.NotNil(t, err)
	})
}

func main() {
	if err =initFeatureFlags("fail_empty.json"); err != nil {
		log.Fatalf("Feature Flags Error: %s", err)
	}
}
```
Apologies if it doesn't work as written, I stripped a bunch out to generalize it.

In my environment, going by this example, the "fail if json file is empty" assert.NotNil fails because err is nil, however when main() is called and uses the same file the log.Fatalf fails with `{"level":"fatal","msg":"Feature Flags Error: Error initializing feature flags: impossible to retrieve the flags, please check your configuration: unexpected end of JSON input","time":"2024-02-21T11:14:30-06:00"}
`.

I've manually copied & pasted the fileretriever.Retriever setup into my code so that I could add logging and modified the initFeatureFlags function to use it, however the copied Retriever function was never hit during the test run, but was during main() being run. I thought it might be related to https://github.com/thomaspoignant/go-feature-flag/issues/858 and there was some sort of non-blocking race conditioning happening, however after reading that the init function happens synchronously and the test was consistently failing in the same way each run and has never passed I believe I've ruled out that possibility.

And something that just occurred to me, the first test "fail if json file doesn't exist" passes because the file doesn't exist at all. So I got the idea to swap them around in the testing order and then it does fail in the same way that the "fail if json file is empty" test fails. In digging through the code, I'm suspecting it is this block of code that is causing my issue: https://github.com/thomaspoignant/go-feature-flag/blob/main/feature_flag.go#L32
	
I hope this was enough. I can elaborate further if necessary.

**Comment by thomaspoignant** [comment]
Hey @MRyanPW, I've looked at your example and I think I understand what is the problem.
Based on your example, it seems that you use GO Feature Flag as a singleton in your application, but also in your example, you try to call the `Init` method multiple time which is not expected from a Singelton point of view.

In your tests I will recommend you to use `ffclient.New` instead of `ffclient.Init`, it will create **multiple instance of GO Feature Flag**, which is actually what you need if you want each test to have an unique context for feature flagging.

You can know more about it in the doc: https://gofeatureflag.org/docs/go_module/configuration#working-with-multiple-go-feature-flag.

Please let me know what you think about this approach and if it works for you 🙏.

**Comment by MRyanPW** [comment]
That's what I needed!

I was assuming I would only be using 1 instance and didn't make the connection between that and the tests being multiple. And for what it's worth I actually prefer having an object to work rather than the implicit singleton to with, so this is a much better solution for me.

Thank you very much!

**Comment by thomaspoignant** [comment]
Glad it helped 👍 
Implicit singleton is here because it is easy to use, but yes for advance usage like yours it is much better to use directly an instance you manage.
