### ISSUE TITLE
Potential memory leak when using s3 retriever

### ISSUE THREAD

**Issue by kingrain94** [thomaspoignant/go-feature-flag#1598]
### Your question

When I use s3 retriever with polling interval is 5 seconds, the memory usage is increased constantly, that's easy to lead memory leak incident.
So I want to ask how do I refresh the memory usage (or clear the old cached flags) of ffclient once we reload the new flags from s3 config file?

**Comment by thomaspoignant** [comment]
Hey @kingrain94, thanks for raising this.
I have a small idea of what can go wrong here, I will have a look at it.

But can you tell me how you've detected the potential leak? 
It will help me to reproduce on my side.

**Comment by kingrain94** [comment]
hi @thomaspoignant 
Thank you for quick response!

>But can you tell me how you've detected the potential leak?

I'm monitoring resource by datadog and detected that memory is increased constantly from the day we applied `go-feature-flag`.

>Also which version of the s3retriever are you using? s3retriever or s3retrieverv2?

I'm using `s3retriever`, is there any issue with it?

**Comment by kingrain94** [comment]
>I ask myself whether the leak is on the retriever or somewhere else in the library, but I am not sure.
>Did you experience the same kind of leak using a different retriever?

Actually I've only used s3 retriever since go live for go-feature-flag.
This is my ffclient initial code:
```go
err := ffclient.Init(ffclient.Config{
		PollingInterval: 5 * time.Second,
		Retriever: &s3retriever.Retriever{
			Bucket: env.S3Bucket,
			Item:   env.S3Key,
			AwsConfig: aws.Config{
				Region:           aws.String(env.Region),
				S3ForcePathStyle: aws.Bool(true),
				Endpoint:         aws.String(env.Endpoint),
			},
		},
	})
if err != nil {
	panic(err)
}
```

**Comment by thomaspoignant** [comment]
@DucVuMinh let me unassign myself and you will be able to assign it to you

**Comment by DucVuMinh** [comment]
I create a pull request to add logic close and remove file for old version of receiver S3.
And with my bench mark, I found that with S3 receiver the PollingInterval should be about >= 30s. If it's too fast, such as 5s, it will make a memory issue. Hope this help the guide with memory issue

**Comment by thomaspoignant** [comment]
Hey @DucVuMinh I am curious, how did you find out about the polling interval?
Do you think it is an issue with the S3 SDK?

**Comment by DucVuMinh** [comment]
hello @thomaspoignant for the late response, this issue is relate to S3 SDK. I found out the threshold by benchmark it in my server.
