### ISSUE TITLE
(feature) <PHP provider>

### ISSUE THREAD

**Issue by cdvv7788** [thomaspoignant/go-feature-flag#1714]
### Requirements

Any plans to provide a PHP provider?
I think this project is pretty nice, specially in the way it can retrieve the feature flags (flagd feels limited in that regard).
I want to give it a try in both Python and PHP, so that's my only concern.

**Comment by thomaspoignant** [comment]
Hello @cdvv7788,
This is something I would like to have, but my PHP skills are limited which is why I haven't started it yet.
If you have skills in PHP I would be more than happy to work on this with you, creating a provider is relatively easy.

**Comment by thomaspoignant** [comment]
@cdvv7788 sorry about the time it took, but I had finally some time to work on a PHP provider.
A pull request is open here https://github.com/open-feature/php-sdk-contrib/pull/106 if you want to have a look 👀 , and feel free to review it, it will be helpful.

As soon as it is merged I will notify you.

**Comment by thomaspoignant** [comment]
@cdvv7788 GO Feature Flag is now supporting PHP 🙌.
You can try it if you want and provide any feedback on your experience with it.
