### ISSUE TITLE
(feature) Add an option to not retrieve flag values on weekend or dev environment to reduce carbon footprint

### ISSUE THREAD

**Issue by sarvsav** [thomaspoignant/go-feature-flag#1716]
### Requirements

Would it be nice to have to declare the freeze option in the config, when the feature flag will not retrieve the flag information from the network? It will reduce the CPU, network calls, and the cost. What do you think about it? I would love to work on it, if you approve and would be great to have your guidance on it.

#green-development 🌳

**Comment by thomaspoignant** [comment]
Hey @sarvsav what do you mean by not retrieving from the network?
Do you mean not calling the `retriever` and keep using the default value instead?

Because there is the [`Offline`]( https://pkg.go.dev/github.com/thomaspoignant/go-feature-flag#Config) who is doing exactly that.

**Comment by sarvsav** [comment]
Yes you are right, not calling the retriever all the time. And, with [Offline](https://github.com/thomaspoignant/go-feature-flag/blob/3839b94cd3fe86e166fe1bf7ab5f4b521ba048d4/config.go#L68), we can not define the time period as per my understanding. For example, I want my flags to be retrieve only on Weekdays and not on weekends, or late night (10 pm - 7am).

**Comment by thomaspoignant** [comment]
While I understand it may be useful, I would prefer not to introduce this inside `go-feature-flag`, but an option could be able to put the system `Offline` after the initialization.

This will allow us to have the same feature as you mentioned but managed from outside of the library.

It can look like this:

```go
goff, err := ffclient.New(ffclient.Config{
  PollingInterval: 3 * time.Second,
  Retriever:      &fileretriever.Retriever{
    Path: "flag-config.goff.yaml",
  },
  Offline: false,
})
defer goff.Close()


//...
// a function with your scheduling logic to put goff offline
goff.setOffline(true)
```

Why do I think this is a better solution?
1. We don't force anyone to follow our system to put it online and offline
2. It brings more flexibility to the user of goff to put it offline the way they want.

**Comment by sarvsav** [comment]
I agree with the above approach, and it will keep the service simple. It will avoid the complexity of understanding the new config key, timezone difference and other minor issues. May I have your approval to implement this feature?

**Comment by thomaspoignant** [comment]
sure you can follow the [contribution guidelines](https://github.com/thomaspoignant/go-feature-flag/blob/main/CONTRIBUTING.md#pull-requests) if you want to assign the issue to you.

**Comment by thomaspoignant** [comment]
Sorry i forgot to remove myself from the assignment.
I have assigned it to you @sarvsav.

**Comment by thomaspoignant** [comment]
Closing this issue because a new functionality has been added to the go module to set offline the retrievers #1774
