### ISSUE TITLE
Did 1.26.0 release get re-tagged?

### ISSUE THREAD

**Issue by chenrui333** [thomaspoignant/go-feature-flag#1771]
👋 looks like the tarball checksum for 1.26.0 release got changed, raise this issue to confirm if there was re-tagging. Thanks!

relates to https://github.com/Homebrew/homebrew-core/pull/169476

**Comment by thomaspoignant** [comment]
@chenrui333 yes it has been re-tagged due to release process changes.

How can I fix the brew PR ?
