### ISSUE TITLE
(bug) targetingKey does not work in the query of targeting rule using OFREP

### ISSUE THREAD

**Issue by tomflenner** [thomaspoignant/go-feature-flag#1898]
### Observed behaviour

With OFREP, when using targetingKey in a query of a targeting rule the evaluation is not working.

For example, check if targetingKey is in list return always default variation for a boolean flag.

### Expected Behavior

The targeting rule execute the query with the evaluation context and return the good variation if targetingKey is in list for example

### Steps to reproduce

With the OFREP web sdk (client-side feature flaging) and this boolean feature flag :
```
{
  "foo-flag": {
    "variations": {
      "true": true,
      "false": false
    },
    "targeting": [
      {
        "name": "Rule 1",
        "query": "targetingKey in [\"toto\"]",
        "variation": "true"
      }
    ],
    "defaultRule": {
      "variation": "false"
    }
  }
}
```

Try set the value of targetingKey to "toto" and get the value of the foo-flag will result to false instead of true.

**Comment by tomflenner** [comment]
Note : discussed with @thomaspoignant on slack private channel.

This issue is due to the fact that in GOFF targetingKey is mapped to key.

Some legacy code need to be removed here : https://github.com/thomaspoignant/go-feature-flag/blob/f9f2fe7e84af28e17ffdb81fb3713f76a778e2f7/cmd/relayproxy/ofrep/evaluate.go#L208

**Comment by tomflenner** [comment]
Maybe we can change this implementation : https://github.com/thomaspoignant/go-feature-flag/blob/f9f2fe7e84af28e17ffdb81fb3713f76a778e2f7/internal/flag/rule.go#L253C1-L259C2 which is the function that return the query which will be executed by the library https://github.com/nikunjy/rules

To replace targetingKey to key instead with something like that for example :

```
func (r *Rule) GetTrimmedQuery() string {
	splitQuery := strings.Split(r.GetQuery(), "\n")
	for index, item := range splitQuery {
		splitQuery[index] = strings.TrimLeft(item, " ")
	}
	trimmedQuery := strings.Join(splitQuery, "")
	return strings.ReplaceAll(trimmedQuery, "targetingKey", "key")
}
```

**Comment by thomaspoignant** [comment]
@tomflenner I had some reflection about it and I thinking keeping `targetingKey` and `key` is probably the easiest way to go.
I am afraid that changing the rule can have more side effect.
I will also try to do some documentation to explain that there is some restricted keys inside the evaluation context.

I will open a PR in few minutes for it.

**Comment by tomflenner** [comment]
@thomaspoignant ok ! If we're more sure about this fix let's go ! 🚀

In fact the documentation must mention that `targetingKey` and `key` are two restricted key 👍🏻

Maybe we can improve the UI of the editor to be able to select `targetingKey` and `key` to facilitate writing rules based on these restricted keys ?

**Comment by thomaspoignant** [comment]
I have created an issue fir the documentation.

And yes it may be a good idea for the editor ro improve it.
