### ISSUE TITLE
(change) Propose updating the base image of relay proxy to Debian 12 (bookworm)

### ISSUE THREAD

**Issue by itchyny** [thomaspoignant/go-feature-flag#1909]
### Motivation

We're using the Docker image of the relay proxy, but we noticed the `openssl 1.1.1w-0+deb11u1` in the image is a bit old (EOL on 11th September 2023). Could you update the base image to Debian 12? Thanks for maintaining the product.

### Requirements

Update the base image of relay proxy to Debian 12.

**Comment by thomaspoignant** [comment]
Hey @itchyny, this is a good idea I haven't check the dockerfile for a while.
I will open a PR for that.

**Comment by thomaspoignant** [comment]
The bump of the version will be available in the next release.
