### ISSUE TITLE
(bug) Report error of yaml validation

### ISSUE THREAD

**Issue by millotp** [thomaspoignant/go-feature-flag#2090]
### Observed behaviour

When trying to validate that a config file is valid, we create a new client with a the invalid yaml, but since #2052, all validation errors are overwritten by the `no persistent flag available` error, and we loose the original error ([this one](https://github.com/thomaspoignant/go-feature-flag/blob/v1.31.0/feature_flag.go#L107)) that contains the useful information (for example `yaml: line 20: could not find expected ':'`).

Even though we don't use the `persistent local disk` feature, the errors stills shows up, is there a way to disable this feature completely when we don't need it in order to get the real error ?

### Expected Behavior

The original error should be returned when the persist to local disk feature is not used

### Steps to reproduce

- Create an invalid yaml
- Initialize the client
- We always get the error `no persistent flag available`

**Comment by thomaspoignant** [comment]
@millotp thanks for raising the issue.
I will have a look at it and try to fix this as soon as possible.

**Comment by thomaspoignant** [comment]
I've open a PR #2092.
I need to do some additional tests and i will release a new version.

**Comment by thomaspoignant** [comment]
A new version `v1.31.1` is available now.

**Comment by millotp** [comment]
thanks a lot for the fix !
