### ISSUE TITLE
(change) Make Notifier interface publicly implementable 

### ISSUE THREAD

**Issue by shezadkhan137** [thomaspoignant/go-feature-flag#214]
# Motivation
Make the Notifier interface publicly implementable.

Hi, thanks for making this library! I would like to output feature flag changes to our internal Grafana via the Annotations API. 

The current Webhook notifier doesn't satisfy our need, as we would like to format the text for the annotation based on the diff. We could do this via an intermediate web server that translates the Webhook notifier payload for Grafana, but it would be nice to do it without the intermediate server.  

# Requirements
Ideally, go-feature-flag should allow the notifier interface to be implemented publically and support custom notifiers passed in completely via the Config. Currently is not possible because the [GetNotifier](https://github.com/thomaspoignant/go-feature-flag/blob/8be9b79c852849b99cf1b5abecda5f5e7524d24b/config.go#L76) interface returns the internal Notifier interface. Also, the Notifier interface accepts an internal [model.DiffCache](https://github.com/thomaspoignant/go-feature-flag/blob/8be9b79c852849b99cf1b5abecda5f5e7524d24b/internal/notifier/notifier.go#L10) struct. 

Would it be possible to make these part of the public API? I think it may be just a matter of taking it out of the internal package and into a public notifier package?

I'm more than willing to put a PR in, if you are okay with making it public. Thanks!

**Comment by urso** [comment]
Other interfaces like `Exporter` face the same issue. Maybe it would make sense to rename `internal` to `pkg` or move some more packages from `internal` one level up?

**Comment by thomaspoignant** [comment]
@shezadkhan137 Sorry I just see you issue today.
I will check what I can do to change the way the notifier works to make them public.

@urso thanks for the idea I will look at them.

**Comment by thomaspoignant** [comment]
> Other interfaces like `Exporter` face the same issue. Maybe it would make sense to rename `internal` to `pkg` or move some more packages from `internal` one level up?

I have exposed `FeatureEvent` publicly for the `Exporter`, now it should work. See #225.

**Comment by thomaspoignant** [comment]
I am really sorry for the delay @shezadkhan137, I have released a v0.20.0 version that allows creating custom `notifiers`.
I have added an example of how to do that in the [documentation]().

Feel free to give me any feedback if it works well for you.

**Comment by shezadkhan137** [comment]
Wow, thanks so much @thomaspoignant. Will give it a go and let you know :-)

**Comment by urso** [comment]
> I have exposed FeatureEvent publicly for the Exporter, now it should work. See https://github.com/thomaspoignant/go-feature-flag/pull/225.

Thanks!
