### ISSUE TITLE
(feature) Add pre-defined labels of the OCI Image Format Specification to Docker images

### ISSUE THREAD

**Issue by itchyny** [thomaspoignant/go-feature-flag#2249]
### Requirements

In order to provide metadata for Docker image users, the OCI Image Format Specification is widely accepted. I'd like to get these metadata from the go-feature-flag-relay-proxy image.
https://github.com/opencontainers/image-spec/blob/main/annotations.md#pre-defined-annotation-keys

Looking into the GoReleaser document, there labels can be applied by customizing `build_flag_templates`.
https://goreleaser.com/customization/docker/#customization

Especially, I would like to see `org.opencontainers.image.source` and `org.opencontainers.image.revision` which are used by Renovate.
https://docs.renovatebot.com/modules/datasource/docker/#description

**Comment by thomaspoignant** [comment]
@itchyny this is good idea to add those.
I am currently in vacation but this is something I can look at when I am back.

If you want you can also open a PR.
