### ISSUE TITLE
(feature) DTO should not be internal

### ISSUE THREAD

**Issue by ribrdb** [thomaspoignant/go-feature-flag#2317]
### Requirements

It seems like the DTO package should be public so other tools can read/write the flags files. For example, a custom resolver may need to translate flags from some other format. Itt'd be safer to do that by just importing a library instead of having to re-implement the serialization.

**Comment by thomaspoignant** [comment]
Hey @ribrdb sorry for my late reply.
Yes it could be feasible to have the DTO public, I am just wondering what exactly you are trying to achieve.
Because all the `retrievers` are not dealing directly with the DTO it is used only internally.

**Comment by ribrdb** [comment]
I have two ideas I'm thinking about:

1. A resolver that reads flags from a DB, where the db is storing flags in a different format. E.g. one row per flag. The resolver would need to be able to convert those into config file format.
2. I want to write a command line tool to parse and edit the config files. E.g. I want the tool to be able to add a new flag, or change the rollout of a flag inside the config file.

**Comment by thomaspoignant** [comment]
@ribrdb ok I understand and I understand completely your need.
The only problem I see is that the DTO will not be for internal use only and there is a risk of breaking it, but since we are very rarely changing it, it may be acceptable.

**Comment by thomaspoignant** [comment]
@ribrdb the dto is now outside of the internal package and can is available [here](https://github.com/thomaspoignant/go-feature-flag/tree/main/model/dto).

**Comment by ribrdb** [comment]
thanks!
