### ISSUE TITLE
Remove migration cli code

### ISSUE THREAD

**Issue by thomaspoignant** [thomaspoignant/go-feature-flag#2402]
> [!WARNING]  
> As mention in the issue #2398 we have decided to drop the support of the `v0.x.x` flag format. 
> *Before creating a pull request for that, please check in the main issue if is the right moment to do it.*

After we have stopped releasing the `go-feature-flag-migration-cli`  *(see #2400)*, we can now safely delete the code of the migration-cli. 

To do this we should delete everything that is under the [`cmd/migrationcli`](https://github.com/thomaspoignant/go-feature-flag/tree/main/cmd/migrationcli) folder.

**Comment by Light2Dark** [comment]
/assign-me
hii again, let me try this! I think it's relatively simple.
