### ISSUE TITLE
(change) Change the way the S3 client is instantiated in the exporter/retriever

### ISSUE THREAD

**Issue by hoangnv-bkhn** [thomaspoignant/go-feature-flag#2451]
### Motivation

Currently, `AwsConfig` is the only parameter used to configure the S3 client to use (while AWS offers much more)
https://github.com/thomaspoignant/go-feature-flag/blob/main/exporter/s3exporterv2/exporter.go#L71
This limits the functionality that AWS provides.

In my case, I need to set some additional configurations for the S3 client such as `EndpointResolverV2` as well as `ForcePathStyle` to facilitate inter-container communication when using localstack in local development.
And I can't find a way to set these in `AwsConfig`.

More specifically...
Suppose I set the alias for my localstack in the network as `localhost.localstack.cloud`
Without configuring the above settings, the s3 client will default to the following path to put the object
`{bucket-name}.s3.localhost.localstack.cloud:4566`
It will always resolve to `127.0.0.1`, which is wrong and the expected value should be the IP of the localstack on the network.
This will be solved by forcing the S3 client to work with path style instead of domain
So, everything would be resolved if I could pass additional configuration when initializing the S3 client

This is what I encountered, and there are likely to be many other requirements related to configuring how the S3 client works
So it makes sense to provide as many of them as possible.

### Requirements

Add configuration parameters to fully support the S3 configuration provided by AWS
https://github.com/aws/aws-sdk-go-v2/blob/main/service/s3/api_client.go#L448
From there, the S3 client will be initialized with the desired configurations

Possible solutions to consider: [Functional Options Pattern](https://golang.cafe/blog/golang-functional-options-pattern.html)

**Comment by thomaspoignant** [comment]
Hello @hoangnv-bkhn thanks for your issue.
I have a couple of question to understand exactly your problem.

Are you using the relay proxy or directly the go module?
I am not 100% familiar with the aws SDK but if I understand correctly your issue, your are talking about some parameters of the client that cannot be changed based on the config right?

**Comment by hoangnv-bkhn** [comment]
Hi @thomaspoignant, 
Thanks for the quick reply!

> Are you using the relay proxy or directly the go module?

 I'm using the Go module

> your are talking about some parameters of the client that cannot be changed based on the config right?

I think more precisely it is not initialized with the configuration I want.
As you can see, this is how the S3 client in the `go-feature-flag` is initialized, it is just initialized based on the `AwsConfig`
<img width="695" alt="image" src="https://github.com/user-attachments/assets/bec14c1f-df25-4d85-8c02-0a8c5a87f4ab">
In fact, AWS also supports an additional option parameter `optFns ...func(*Options)` in the `NewFromConfig` function.
This gives us more flexibility in configuring the S3 client.
<img width="596" alt="image" src="https://github.com/user-attachments/assets/579747e2-5963-436e-9c0e-72b29c48143d">

**Comment by hoangnv-bkhn** [comment]
Yeah, that's right!
Btw, I'm working with the exporter but it would be better if we had it on both the exporter and the retriever.

**Comment by hoangnv-bkhn** [comment]
Btw, I haven't contributed before but I am interested in contributing by solving this issue.
Is that possible? Or do you already have plans to implement it yourself?

**Comment by thomaspoignant** [comment]
@hoangnv-bkhn It will be even better if you want to contribute to this.

You can assign the issue to yourself by following the [contributing guidelines](https://github.com/thomaspoignant/go-feature-flag/blob/main/CONTRIBUTING.md#pull-requests).
