### ISSUE TITLE
(bug) Tracing no longer working

### ISSUE THREAD

**Issue by hairyhenderson** [thomaspoignant/go-feature-flag#2479]
### Observed behaviour

Since https://github.com/thomaspoignant/go-feature-flag/pull/1503, the OTel service's `Init()` method is no longer being called. As a result, tracing is no longer working.

### Expected Behavior

Tracing should work!

**Comment by hairyhenderson** [comment]
I've got a local fix in play, PR coming soon...

**Comment by thomaspoignant** [comment]
Hey @hairyhenderson I am sorry for that, I did not spotted this regression.
If you have a PR ready can you open it and we can work from there.

**Comment by hairyhenderson** [comment]
I've got a fix up here: https://github.com/thomaspoignant/go-feature-flag/pull/2482
