### ISSUE TITLE
(question) Custom json retriever from API

### ISSUE THREAD

**Issue by sswastioyono18** [thomaspoignant/go-feature-flag#2506]
### Your question

Hi, I wanted to know if it is possible to have json retriever for the config file because I have a service similar like firebase that stores config as json file

I want to leverage that service as json provider, the client should call the API and parse the json returned from that service as the input retriever

**Comment by sswastioyono18** [comment]
nevermind, I just saw that i can use custom retriever easily..
https://gofeatureflag.org/docs/go_module/store_file/custom

closing this one

**Comment by thomaspoignant** [comment]
Hello @sswastioyono18 
This is definitely something doable to create a custom retriever that change the format into the GOFF format.

I am just struggling to see if we can do this as a generic way for any format.
Can you answer those questions it will help me:
- Are you using the relay-proxy or the go module?
- Can you share an example of the transformation you would like to do between the 2 formats?

**Comment by thomaspoignant** [comment]
> nevermind, I just saw that i can use custom retriever easily.. https://gofeatureflag.org/docs/go_module/store_file/custom
> 
> closing this one

Note that this is not available for the relay-proxy but only if you use the GO Module.

**Comment by sswastioyono18** [comment]
> Hello @sswastioyono18 This is definitely something doable to create a custom retriever that change the format into the GOFF format.
> 
> I am just struggling to see if we can do this as a generic way for any format. Can you answer those questions it will help me:
> 
> * Are you using the relay-proxy or the go module?
> * Can you share an example of the transformation you would like to do between the 2 formats?

Whoopsie somehow I forgot to close this issue and marked it as solved 😅
I am using the go module and it turns out very easy to do this.
We create a key `feature-flag` and store the json goff value into the Key Value service we have.
Inside our caller service, we bootstrapped the custom retriever to call our KV service and return the GOFF payload we needed (need to do some parsing related to the payload we want to get).

Then we just implement the evaluation logic where we need to judge based on the feature flag similar with the common example on goff website.

The unit test also need to be modified since we also have to inject the custom retriever if needed.

```
type CustomRetriever struct {
}

func (c CustomRetriever) Retrieve(ctx context.Context) ([]byte, error) {
	httpClient := myapiClient(option{
		BaseURL:       "some-url;,
		SecretKey:     "secret",
		PlatformName:  "pwa",
		ClientName:    "gofeature",
		ClientVersion: "1.0.0",
		ApiVersion:    "1.0.0",
	})

	result, errClient := httpClient.Get(context.Background(), "feature-flag", "test_ff", "1.0.0")
	if errClient != nil {
		log.Err(errClient).Msgf("errClient")
		return nil, errClient
	}

	return result, nil
}

func main() {

	//Init ffclient with a HTTP retriever.
	err := ffclient.Init(ffclient.Config{
		PollingInterval: 10 * time.Second,
		LeveledLogger:   slog.Default(),
		Context:         context.Background(),
		Retriever:       &CustomRetriever{},
	})

	// Check init errors.
	if err != nil {
		log.Fatal().Msgf("error initializing ffclient: %v", err)
	}
	// defer closing ffclient
	defer ffclient.Close()

	for i := 0; i < 100; i++ {
		time.Sleep(1 * time.Second)
		// create users
		user1 := ffcontext.
			NewEvaluationContextBuilder(fmt.Sprintf("user_%d", i)).
			Build()

		// user1
		user1HasAccessToNewAdmin, err := ffclient.BoolVariation("my-first-flag", user1, false)
		if err != nil {
			// we log the error, but we still have a meaningful value in user1HasAccessToNewAdmin (the default value).
			log.Printf("something went wrong when getting the flag: %v", err)
		}

		fmt.Printf("User%d  access to new admin: %v\n", i, user1HasAccessToNewAdmin)
	}

}
```
