### ISSUE TITLE
Make `getFlagFromCache` method public

### ISSUE THREAD

**Issue by marcosnils** [thomaspoignant/go-feature-flag#251]
# Motivation

I'm running `go-feature-flags` in my API and in my `health` endpoint I'd like to return all the `flags` that I have configured and the current version in cache. I see that the `getFlagFromCache` method could give me all the information that I need but it's currently private. Is it ok if we made it public? Happy to send a PR to address that.

**Comment by thomaspoignant** [comment]
Hey @marcosnils this is a good idea and I kinda need it too for one of my projects 😄 
I am not sure that putting `getFlagFromCache` as public will be enough, but if you want to have a look on how to do that you can make a proposal.

**Comment by thomaspoignant** [comment]
@marcosnils I have seen your PR and this is not what I had in mind when I first checked this issue.

With this solution, you have to call the `GetFlagFromCache` function for all the flags one by one to get the value.
Is it what you wanted? I was also thinking about a function that returns the state of the cache at a specific moment.

**Comment by marcosnils** [comment]
> Is it what you wanted?

This is what I need in the immediate term, yes. I'm  that creating a new method to retrieve all flags would be more useful. I'll make a quick change for this and update the PR :raised_hands:

**Comment by marcosnils** [comment]
:wave: just made a new commit that allows all flags from cache to be exposed. Shall we continue the discussion on the PR?

**Comment by thomaspoignant** [comment]
> @thomaspoignant. gente ping!

Sorry @marcosnils it was a crazy week, let me check that on Monday if it is ok for you?
