### ISSUE TITLE
(feature) Microsoft Teams Notifier

### ISSUE THREAD

**Issue by thomaspoignant** [thomaspoignant/go-feature-flag#2556]
### Requirements

As of Today GO Feature Flag is able to notify difference sources when a flag is changing _(see [relay proxy configuration](https://gofeatureflag.org/docs/relay_proxy/configure_relay_proxy#type-notifier) and [go module](https://gofeatureflag.org/docs/go_module/notifier))_.

Slack is supported since a lot of companies are using it, but some companies prefer to use Microsoft Teams instead.

To support teams we can implement a new notifier using the [Teams API](https://learn.microsoft.com/en-us/graph/api/chatmessage-post?view=graph-rest-1.0&tabs=http) to send the message of flag change inside a teams channel.

_A good inspiration to build this is to follow what is done for the slack notifier integration: https://github.com/thomaspoignant/go-feature-flag/tree/main/notifier/slacknotifier._

**Comment by martinvibes** [comment]
hello @thomaspoignant i would love to work on this issue :)

**Comment by CollinsC1O** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/go-feature-flag).

### My background and how it can be leveraged
 I will love to work on this

**Comment by Josue19-08** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/go-feature-flag).

### My background and how it can be leveraged
My name is Josué. I'm part of the Dojo Coding community and have worked on several projects, including some in Unity. I have experience with C#, .NET, Java, JavaScript, Angular, and Node.js. I love contributing to open-source projects, whether it's fixing bugs, adding new features, or improving documentation.

### How I plan on tackling this issue
I previously worked on a similar project where I implemented notifications via Slack and Discord for system changes. For this task, I would use the Microsoft Teams API to create a notifier for flag changes, following the same structure as the Slack notifier in GO Feature Flag. This would ensure consistent functionality and easy integration into both the relay proxy and the Go module.
