### ISSUE TITLE
(feature) Azure Blob Storage retriever

### ISSUE THREAD

**Issue by thomaspoignant** [thomaspoignant/go-feature-flag#2558]
### Requirements

In order to continue GO Feature Flag support to major cloud provider we want to bring the same support as GCP and AWS for Azure.

To do this, we want to let GO Feature Flag users the possibility to store their configuration files into Azure Blob Storage.

For this, we want to have a Azure Blob Storage `retriever` that will get the configuration directly from the Azure service.

**Things to take in consideration:**
- We can use the azure SDK to be able to communicate with BlobStorage (https://github.com/Azure/azure-sdk-for-go/tree/main/sdk/storage/azblob)
- We should be able to give the credentials through the normal mechanism of authentifcation of the GO sdk.
- This should work both as GO module and in the relay-proxy.

_An example of PR to add a new retriver https://github.com/thomaspoignant/go-feature-flag/pull/1717/files_

**Comment by Josue19-08** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/go-feature-flag).

### My background and how it can be leveraged
My name is Josué. I'm part of the Dojo Coding community and have worked on several projects, including some in Unity. I have experience with C#, .NET, Java, JavaScript, Angular, and Node.js. I love contributing to open-source projects, whether it's fixing bugs, adding new features, or improving documentation.


### How I plan on tackling this issue
I’d use the Azure SDK to build a simple retriever that grabs configuration files from Azure Blob Storage. It’ll work just like the existing support for GCP and AWS, using the usual Go SDK authentication methods. The retriever will run smoothly both as a Go module and in the relay-proxy. I’ll follow the example provided to keep things consistent and straightforward.

**Comment by Josue19-08** [comment]
Excited to get started.

**Comment by Josue19-08** [comment]
@thomaspoignant  Sir, I don't think I can finish this issue in time. I'm so sorry, I think it's best to reassign myself so someone else can work on it. Thanks for the opportunity.

**Comment by bigherc18** [comment]
Hello! I'm an experienced Software Engineer with over 5 years of experience. Although I'm primarily using Python right now, I've written and loved working with Go in the past, and I'd love the chance to get back to it.

I looked into Go Feature Flag and the Open Feature standard, and they really resonated with me—I'd be more than happy to contribute!

Regarding the issue, I'll begin by checking the linked PR for an example to add a new retriever, then check the `azure-sdk-for-go` documentation, and jump right into implementing it!

**Comment by 0xdevcollins** [comment]
May I take this issue on?

**Comment by thomaspoignant** [comment]
@bigherc18 you can go for it, I'll assign it to you.

**Comment by bigherc18** [comment]
> @bigherc18 you can go for it, I'll assign it to you.

Thanks, I'll start working on it

**Comment by bigherc18** [comment]
Hi @thomaspoignant, I'm currently having issues with my Mac, and unfortunately, the older computer I tried to use isn't up to the task. I’ll need to step back from this issue for now, but I’d be glad to contribute when I’m back up and running. Thanks for understanding!

**Comment by Abeeujah** [comment]
Hi @thomaspoignant can I work on this?

**Comment by thomaspoignant** [comment]
@Abeeujah yes you can assign yourself
