### ISSUE TITLE
(feature) Azure BlobStorage exporter

### ISSUE THREAD

**Issue by thomaspoignant** [thomaspoignant/go-feature-flag#2559]
### Requirements

In order to continue GO Feature Flag support to major cloud provider we want to bring the same support as GCP and AWS for Azure.

To do this, we want to let GO Feature Flag users the possibility to export their flag usage to Azure BlobStorage.
For this, we want to have a Azure Blob Storage `exporter` that will store all the exported data directly to Azure.

**Things to take in consideration:**
- We can use the azure SDK to be able to communicate with BlobStorage (https://github.com/Azure/azure-sdk-for-go/tree/main/sdk/storage/azblob)
- We should be able to give the credentials through the normal mechanism of authentifcation of the GO sdk.
- This should work both as GO module and in the relay-proxy.

**This exporter will be very similar to the S3 exporter and Google Storage exporter.**

_An example of PR to add a new exporter https://github.com/thomaspoignant/go-feature-flag/pull/1745/files_

**Comment by CollinsC1O** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/go-feature-flag).

### My background and how it can be leveraged
Hello I'm a front-end and a blockchain developer and will love to work on this issue. Please assign

**Comment by Abeeujah** [comment]
Hi @thomaspoignant can I work on this?

**Comment by thomaspoignant** [comment]
@Abeeujah sure go for it, I'll affect it to you.

**Comment by Abeeujah** [comment]
Hi @thomaspoignant would you prefer auth via azblob or via azidentity or you wouldn't mind having both as an option?
