### ISSUE TITLE
(change) Move retrievers into sub-pacakges (or external libs?)

### ISSUE THREAD

**Issue by urso** [thomaspoignant/go-feature-flag#256]
# Motivation

The go-feature-flag library provides a nice and hopefully growing list of retrievers. Unfortunately all retrievers are made available in the top-level package, which means that all projects that do depend on go-feature-flag automatically pull in and compile all those dependencies, no matter what. With the recent addition of the kubernetes client the compile, lint times, and binary file sizes have increased quite significantly. In my case each each have doubled the least... and my local pre-commit hook running golangci-lint even went up to 200s.

# Requirements

Users of go-feature-flag should be allowed to pull in only the dependencies they actually need. This can be achieved by moving the retrievers into their own packages like `go-feature-flag/retrievers/...` for example, or moving them into separate Repositories (which might be annoying maintenance wise...).

**Comment by urso** [comment]
Hi, Sorry, I haven't had time to look into the issue yet.

> I would suggest having one package by source type (s3, google, k8s ...).

This works for me.

Alternatively you might consider a layout used by other projects to [opentelemetry-go](https://github.com/open-telemetry/opentelemetry-go), [opentelemetry-collector](https://github.com/open-telemetry/opentelemetry-collector), [Elastic Beats](https://github.com/elastic/beats), [telegraf](https://github.com/influxdata/telegraf/tree/master/plugins). They do not organize packages by integration, but by their own concepts like input, receiver, output, exporter and so on.

In case of the go-feature-flag library this would give us folders like:

```
.../retriever/gcpstorage
.../retriever/http
.../retriever/k8s
.../retrieve/asws3
.../notifier/slack
.../notifier/webhook
.../exporter/...
```

Normally I would put those at the top-level, but you already have ffexporter/ffnotifier packages. Using the by-concept scheme I would do one of these: 
- Rename `ffnotifier` to `notifier` and just move the slack and webhook folders there as sub-packages.
-Introduce a plugin folder with all integration types.

But no strong feelings for one or the other solution on my side. All variants will help with better isolating the integrations and help with discoverability just by browsing the folders on github.

A note about isoation. Given you original idea I think you have considered this already. Other clients like AWS or GCP are huge as well. E.g. the aws sdk v2 was update to reduce its footprint. For this reason one might not want a single `aws` integration folder with all supported services. Still (even in case of AWS) one might want some common helpers for Otel instrumentation or configuring authentication/service discovery, which means that you will likely end up with `internal/aws` package (and similar for other services) in case the number of integration grows. 

In case of `integrations` folder the structure might look like:

```
integrations/
  internal/aws
  gcp/
  k8s/
  s3/
  ...
```

in case of a plugins folder you will end up with

```
plugin/
  internal/aws
  retriever/
    gcp
    s3
    k8s
  notifier/
    slack
    webhook
  exporter/
    dynamodb
    datadog
    elasticsearch
    ...
```

**Comment by urso** [comment]
> Would it be an acceptable change (even if it is a breaking change).

From my point of view I would welcome the change (I mean, I opened the issue :P ). And you are still at 0.25 ;)
Some reorg will also help to keep the project more maintainable in the future. 

I can see how this can affect other people who just update their deps without looking, but CI (build) will fail immediately and it is time to investigate. So far I did find the release notes produced by github (and dependabot in my projects) good enough for your project. If you have a good title + PR description (or git commit text) telling me how to change my code to fix it I'm fine.

**Comment by thomaspoignant** [comment]
Thanks for all the inputs @urso, I will have a look and try to open a pull request for that.

**Comment by thomaspoignant** [comment]
@urso I've made a proposal on this PR #264 if you want to have a look and tell me what you think.
I still need to write the migration doc from the old format to the new one but having feedback would help.

![Screen Shot 2022-07-04 at 18 14 36](https://user-images.githubusercontent.com/17908063/177190975-23bdc4a3-f952-4fea-8f71-e6751324d69e.png)  ![Screen Shot 2022-07-04 at 18 15 21](https://user-images.githubusercontent.com/17908063/177190983-596a0fc5-e7b6-45ae-a191-3b145eb3f1d7.png)

The only thing that I found not idiomatic is when a `retriever` and a `exporter` have the same package name.
You have to rename the **packages** in your imports.


```go
import (
	fileExp "github.com/thomaspoignant/go-feature-flag/exporter/file"
	"github.com/thomaspoignant/go-feature-flag/retriever/file"
// ...
)

func main() {
	// Init ffclient with a file retriever.
	err := ffclient.Init(ffclient.Config{
		PollingInterval: 10 * time.Second,
		Logger:          log.New(os.Stdout, "", 0),
		Context:         context.Background(),
		Retriever: &file.Retriever{
			Path: "examples/retrfile/flags.yaml",
		},
		DataExporter: ffclient.DataExporter{
			FlushInterval:    1 * time.Second,
			MaxEventInMemory: 100,
			Exporter: &fileExp.Exporter{
				OutputDir: "./",
			},
		},
	})
// ...
```

**Comment by urso** [comment]
OK, I tested on of my projects with go-feature-flag `v0.22`, `v0.25.0` (I had to fallback to 0.25.0, as the `rules` dependency did fail to build) and the feature branch regarding compile times and binary size. The project currently uses the file, http, and github retrievers only. 

So far I'm happy with the stats. The restructure is even a few milliseonds faster then `v0.22`.

Testing for `0.25.0`:

```
$ go clean --cache
$ time go build
go build  206,85s user 17,92s system 1562% cpu 14,386 total
$ time go build
go build  3,09s user 0,55s system 790% cpu 0,459 total
$ time go build
go build  2,84s user 0,56s system 791% cpu 0,430 total
$ time go build
go build  2,72s user 0,71s system 739% cpu 0,464 total
$ time go build
go build  2,86s user 0,62s system 775% cpu 0,449 total

File size: 96MB
```

Test output v0.22

```
$ go clean --cache
$ time go build
go build  136,85s user 11,49s system 1805% cpu 8,217 total
$ time go build
go build  2,19s user 0,46s system 768% cpu 0,346 total
$ time go build
go build  2,25s user 0,42s system 753% cpu 0,354 total
$ time go build
go build  2,26s user 0,40s system 772% cpu 0,344 total
$ time go build
go build  2,11s user 0,52s system 778% cpu 0,337 total

File size: 71MB
```

Test Output for #264 
```
$ go clean --cache
$ time go build
go build  125,80s user 10,69s system 1383% cpu 9,866 total
$ time go build
go build  1,97s user 0,43s system 742% cpu 0,324 total
$ time go build
go build  2,06s user 0,34s system 747% cpu 0,320 total
$ time go build
go build  1,94s user 0,37s system 722% cpu 0,320 total
$ time go build
go build  1,76s user 0,67s system 724% cpu 0,334 total


File size: 70MB
```

**Comment by thomaspoignant** [comment]
> For example [opentelemetry collector](https://github.com/open-telemetry/opentelemetry-collector/tree/main/exporter) repeats the names.

I will probably follow this pattern also, it makes it easier to use the lib.

**Comment by thomaspoignant** [comment]
> I had to fallback to 0.25.0, as the `rules` dependency did fail to build

This is probably related to your `antlr` version, you should consider updating it.
The version `0.25.2` should fix this.

> So far I'm happy with the stats. The restructure is even a few milliseonds faster then `v0.22`.
I am happy to hear that, I will still give some love to the pull request to better explain how to migrate and to follow opentelemetry pattern and I let you know when I will release the new version.

**Comment by thomaspoignant** [comment]
@urso The pull request #264 is complete now.

 I amcurious to have your feedback about the PR description, is this good enough for you to migrate easily?

**Comment by urso** [comment]
Thank you! The PR description is very detailed. It contains the why and tells me how to update my code. I left you a small comment on the PR itself.

**Comment by thomaspoignant** [comment]
The version `v0.26.0` is available with the change.
