### ISSUE TITLE
(feature) evaluation command line for local testing

### ISSUE THREAD

**Issue by thomaspoignant** [thomaspoignant/go-feature-flag#2560]
### Context
When using GO Feature Flag in case of percentage based evaluation sometimes you want to know which variant will be returned for a specific evaluation context.

### Proposed solution
We want a command line tool that allow to perform the evaluation directly in the terminal allowing to get a fast feedback on which variant is served for a specific flag configuration file.

#### Example

```shell
$ go-feature-flag-cli evaluate --config ./flag.goff.yaml --flag "my-flag-name" --evaluation-context '{"targetingKey": "03b77ca4-b599-4a43-8241-af67b23b8fc5"}'

{
  "trackEvents": false,
  "variationType": "Variation_1",
  "failed": false,
  "version": "",
  "reason": "STATIC",
  "errorCode": "",
  "value": true,
  "cacheable": true
}

```

The cli should allow those commands:
- `-c` or `--config`: path to the flag configuration file **(mandatory)**
- `-f` or `--flag`: name of the flag to evaluate **(optional)**, if not set the cli should evaluate all the flags available in the `-f` file configuration.
- `-e` or `--evaluation-context`: the evaluation context to validate the flag against the file.

### Implementation
Here are some guidelines for the implementation:
- The code for this command line should be under `cmd/cli`.
- We can use a framework to manage this command line, my choice will be to use [`spf13/cobra`](https://github.com/spf13/cobra).
- Consider that the `evaluate` sub command will be the 1st one but we want to extend the usage of this command line to other need in the future _(maybe move the linter there also)._
- The logic behind this command line will be similar to the `editor` API available [here](https://github.com/thomaspoignant/go-feature-flag/tree/main/cmd/editor).

**Comment by pheobeayo** [comment]
Can I tackle this one?

**Comment by thomaspoignant** [comment]
@pheobeayo there is already a PR open for this one.
You can have a look at it if you want to review it.

**Comment by pheobeayo** [comment]
@thomaspoignant  okay, I will do that

**Comment by SoarinSkySagar** [comment]
Would love to tackle this! I've reviewed the PR made by previous assignee and I'm pretty confident that I can work on top of that one and resolve this issue.
ETA: 3 Days

**Comment by 0xdevcollins** [comment]
Is it okay if I take this?
