### ISSUE TITLE
(feature) Bitbucket retriever

### ISSUE THREAD

**Issue by thomaspoignant** [thomaspoignant/go-feature-flag#2561]
### Requirements

In order to continue GO Feature Flag support to major GIT providers we want to bring the same support as Github and Gitlab for Bitbucket.

To do this, we want to let GO Feature Flag users the possibility to store their configuration files inside Bitbucket.
For this, we want to have a Bitbucket`retriever` that will get the configuration directly from the Azure service.

**Things to take in consideration:**
- We want to use the [bitbucket API](https://developer.atlassian.com/cloud/bitbucket/rest/api-group-source/#api-repositories-workspace-repo-slug-src-commit-path-get) to retrieve the configuration file.
- If we get ratelimited by the API (http 429) we should avoid continuing calling the API to soon and backoff the calls _(this [bitbucket documentation](https://confluence.atlassian.com/bbkb/bitbucket-cloud-rate-limit-troubleshooting-1319575889.html) is really interesting on how to deal with that)_.

_An example of PR to add a new retriver https://github.com/thomaspoignant/go-feature-flag/pull/1717/files_

**Comment by CollinsC1O** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/go-feature-flag).

### My background and how it can be leveraged
Hello I'm a front-end and a blockchain developer and will love to work on this

**Comment by CollinsC1O** [comment]
Hello @thomaspoignant. Wanted to ask if there is a bitbucket repository for the test...

**Comment by CollinsC1O** [comment]
The retriever is up, but the test fails regardless of the repo I test it against, it seems like a specific shape of data is expected...

**Comment by thomaspoignant** [comment]
@CollinsC1O You can test your development against this [repo](https://bitbucket.org/tomypunk/config-repo/src/main/flags/config.goff.yaml).
