### ISSUE TITLE
(change) Export kubernetes interface in kubernetes configmap retriever

### ISSUE THREAD

**Issue by ZhiHanZ** [thomaspoignant/go-feature-flag#266]
# Motivation

Currently the kubernetes configmap retriever only support to pass through rest.Config to it and resolve a clientset during retrieve, restConfig in kubernetes is generally hard to debug, and when something went wrong(nil pointer panic etc), seldom could we extract valuable information from it, while in current retriever example, rest.Config is the only exposed field and we need initialize kubernetes clientset during retrieve.
# Requirements

update the kubernetesConfigRetriever from
```go
// KubernetesRetriever is a configuration struct for a Kubernetes retriever.
type KubernetesRetriever struct {
	Namespace     string
	ConfigMapName string
	Key           string
	ClientConfig  restclient.Config
	client        kubernetes.Interface
}
```
into
```go
// KubernetesRetriever is a configuration struct for a Kubernetes retriever.
type KubernetesRetriever struct {
	Namespace     string
	ConfigMapName string
	Key           string
	ClientConfig  restclient.Config
	Client        kubernetes.Interface
}
```

**Comment by thomaspoignant** [comment]
@ZhiHanZ I don't see the difference between the 2 versions of the `KubernetesRetriever`.

**Comment by thomaspoignant** [comment]
> @ZhiHanZ I don't see the difference between the 2 versions of the `KubernetesRetriever`.

Oh I found the difference, you want to have the `Client` public?
Can you explain me what difference it makes for your usecase?

**Comment by ZhiHanZ** [comment]
Exactly, actually this issue is quite strange, when I use in cluster rest Config directly in my k3d test cluster, the service crash with nil pointer panic, while I write my custom Retriever which adopt  kubernetes clientset, the panic disappeared, I think the root cause maybe some race condition during the runtime, here is my sample custom retriever snippet.
```go
type DatabendConfigMapRetriever struct {
	Name      string
	Namespace string
	Key       string
	Client    kubernetes.Interface
}

func (s *DatabendConfigMapRetriever) Retrieve(ctx context.Context) ([]byte, error) {
	if s.Client == nil {
		return nil, fmt.Errorf("no such client")
	}
	configMap, err := s.Client.CoreV1().ConfigMaps(s.Namespace).Get(ctx, s.Name, v1.GetOptions{})

	if err != nil {
		return nil, fmt.Errorf(
			"unable to read from config map %s.%s, error: %s", s.Name, s.Namespace, err,
		)
	}
	content, ok := configMap.Data[s.Key]
	if !ok {
		return nil, fmt.Errorf("key %s not existing in config map %s.%s", s.Key, s.Name, s.Namespace)
	}
	return []byte(content), nil
}
```

**Comment by ZhiHanZ** [comment]
> Have you tried this [example](https://github.com/thomaspoignant/go-feature-flag/tree/main/examples/retriever_configmap) ?
> 
> I've done it with `minikube` and it is working fine on my side. I have no experience with `k3s` but could it be an issue with this implementation? It would be great if you were able to run the same example with `k3s` and see if you have the same issue.
> 
> By any chance do you have the stack trace of your panic ?
The example works fine, here I tried to replicate the problem but that disappeared. I would close the issue, thanks for your help!
