### ISSUE TITLE
(feature) Python provider API key option

### ISSUE THREAD

**Issue by thomaspoignant** [thomaspoignant/go-feature-flag#2671]
### Requirements

Today in the Python provider there are no option to pass an api key to contact the relay proxy (unlike with other languages).

We should allow the possibility of setting a the api keys in the options and use them to contact the relay-proxy.

**Comment by thomaspoignant** [comment]
Yes sure !

**Comment by thomaspoignant** [comment]
The new version of the python provider is available: https://pypi.org/project/gofeatureflag-python-provider/

**Comment by raizo07** [comment]
Oh wow, I had a look at it yesterday.
