### ISSUE TITLE
(bug) Python Url parse

### ISSUE THREAD

**Issue by cve-zh00** [thomaspoignant/go-feature-flag#2690]
### Observed behaviour

In Python, when a URL with a path like http://0.0.0.0:1031/ff is used, the generic_go_feature_flag_resolver function removes the path and appends "/v1/feature/<flag_key>/eval". This behavior occurs due to how the urljoin function from urllib handles URL composition.

Here’s the relevant code:

`url=urljoin(str(self.options.endpoint),"v1/feature/{}/eval".format(flag_key))`

### Expected Behavior

If I provide a URL with a path, it should be concatenated with the path v1/feature/<flag_key>/eval as follows:

For example:
	•	Given endpoint: http://0.0.0.0:1031/ff/
	•	Expected result: http://0.0.0.0:1031/ff/v1/feature/<flag_key>/eval

However, the actual result is:

http://0.0.0.0:1031/v1/feature/<flag_key>/eval

### Steps to reproduce

Use url with path like 
provider = GoFeatureFlagProvider(
    options=GoFeatureFlagOptions(endpoint="http://0.0.0.0:1031/ff/") 
)

**Comment by cve-zh00** [comment]
@thomaspoignant  If you want I can fix it myself (if it really is an issue)

**Comment by thomaspoignant** [comment]
@cve-zh00 I have provided a fix in the #2707 PR if you want to have a look.
I will release a new version soon.

**Comment by thomaspoignant** [comment]
The new version of the python provider is available: https://pypi.org/project/gofeatureflag-python-provider/
