### ISSUE TITLE
(feature) Should be possible to enable `/debug/pprof` without the additional logging

### ISSUE THREAD

**Issue by hairyhenderson** [thomaspoignant/go-feature-flag#2709]
### Requirements

Right now it's necessary to set `debug: true` to get the pprof endpoint to listen. We like to continuously profile everything with Alloy and Pyroscope, but I'd rather not have requests to `/metrics`/`/health`/etc also be logged.

How about an `enablePprof` config item? I'll issue a quick PR for discussion, but thought you might have other ideas too...

**Comment by thomaspoignant** [comment]
This is actually a good idea.
I think having an option `enablePprof` makes a lot of sense for continuous profiling.

I just would like to keep it enable in debug mode even if `enablePprof` is false.

**Comment by hairyhenderson** [comment]
@thomaspoignant great - see #2710 😁
