### ISSUE TITLE
(bug) web provider infinitive loop trying to connect to websocket

### ISSUE THREAD

**Issue by augustinasrce** [thomaspoignant/go-feature-flag#2753]
### Observed behaviour

If evaluation apiKey is set to wrong one it enter to infinite loop while trying to reconnect.  

### Expected Behavior

Stops after specified amount of retries or stops immediately for this specific error (since there is not way it will be fixed).  

### Steps to reproduce

config eval apiKey to gff service
set wrong one on web provider

**Comment by augustinasrce** [comment]
![image](https://github.com/user-attachments/assets/3d057a3a-787c-4202-976b-1d51426059f4)

**Comment by thomaspoignant** [comment]
With the `websocket` we don't have access to the status code of the query so the only option I see is to have a max number of retries before failing.

I will open a PR for this one.
