### ISSUE TITLE
(doc) react example seems outdated and not very clear

### ISSUE THREAD

**Issue by augustinasrce** [thomaspoignant/go-feature-flag#2755]
### Change in the documentation

in README.md links are not working 

https://github.com/thomaspoignant/go-feature-flag/blob/main/examples/openfeature_react/react-app/src/App.tsx

Implementation it self is not linted/formatted properly
Initialization of OpenFeature sdk is a bit confusing and could be better. 

maybe reusing this would be beneficial 
https://github.com/open-feature/js-sdk/blob/main/packages/react/README.md

**Comment by thomaspoignant** [comment]
Yes it could definitely be better, but can you tell me exactly what you don't like?
The example is very close to the documentation you have linked.

I have open a PR for:
- Implementation it self is not linted/formatted properly
- Fixing the links.

Can you tell me a bit more to make it better.

PR is #2756
