### ISSUE TITLE
upgrade nikunjy/rules module

### ISSUE THREAD

**Issue by juliandanciu** [thomaspoignant/go-feature-flag#348]
The `github.com/nikunjy/rules` module now depends on antlr/v4. This issue is to update go-feature-flags to depend on the newest version of nikunjy/rules (and therefore indirectly depend on antlr/v4).

**Comment by thomaspoignant** [comment]
@juliandanciu I wanted to upgrade the `github.com/nikunjy/rules` package to version `v2.0.0` as you mentioned but this is not possible because the version is not available while doing `go get`.

You can see more info about this in the issue https://github.com/nikunjy/rules/issues/29

**Comment by nikunjy** [comment]
Added https://github.com/thomaspoignant/go-feature-flag/pull/405
