### ISSUE TITLE
(change) Update to nikunjy/rules v1.2.0

### ISSUE THREAD

**Issue by thomaspoignant** [thomaspoignant/go-feature-flag#349]
### Motivation

This is the latest version of `nikunjy/rules`

### Requirements

- [ ] Assess that we don't have any breaking changes
- [ ] Upgrade to `v2.0.0`.

**Comment by thomaspoignant** [comment]
The lib is not ready to be used in v2.
See https://github.com/nikunjy/rules/issues/29#issue-1409121342

**Comment by nikunjy** [comment]
Released a different version instead since it doesn't need a major version bump. 
https://github.com/thomaspoignant/go-feature-flag/pull/405
