### ISSUE TITLE
(bug) Nil pointer dereference when calling a variation without Init

### ISSUE THREAD

**Issue by joshm91** [thomaspoignant/go-feature-flag#360]
### Observed behavior

When calling a variation (e.g., `ffclient.BoolVariation("test", ffUser, false`) without first calling `ffclient.Init()`, a panic happens due to a nil pointer dereference.

This is happening due to directly referencing `ff` here:
https://github.com/thomaspoignant/go-feature-flag/blob/d6dd663b9db656cd1ce261a9e95cd5eb6f9a7135/variation.go#L22-L27

where `ff` is a pointer type:
https://github.com/thomaspoignant/go-feature-flag/blob/d6dd663b9db656cd1ce261a9e95cd5eb6f9a7135/feature_flag.go#L49

that is only set when calling `Init()`:
https://github.com/thomaspoignant/go-feature-flag/blob/d6dd663b9db656cd1ce261a9e95cd5eb6f9a7135/feature_flag.go#L26-L32

### Expected Behavior

I expect the variation call to return an error, _and_ set the return value to the default specified in the call. This behaviour is expected based on the existing documentation, both in function docs:
https://github.com/thomaspoignant/go-feature-flag/blob/d6dd663b9db656cd1ce261a9e95cd5eb6f9a7135/variation.go#L22-L25

and in the documentation site:
https://github.com/thomaspoignant/go-feature-flag/blob/d6dd663b9db656cd1ce261a9e95cd5eb6f9a7135/docs/users.md?plain=1#L70

I _do not_ expect a panic/nil pointer dereference.

### Steps to reproduce

```go
package main

import (
	"fmt"

	ffclient "github.com/thomaspoignant/go-feature-flag"
	"github.com/thomaspoignant/go-feature-flag/ffuser"
)

func main() {
	res, err := ffclient.BoolVariation("test", ffuser.NewUser("test"), false) // <-- This results in nil pointer dereference
	fmt.Println(res)
	fmt.Println(err)
}
```

Results in:
```
➜ go run .
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x2 addr=0x99 pc=0x102cc2230]

goroutine 1 [running]:
github.com/thomaspoignant/go-feature-flag.(*GoFeatureFlag).boolVariation(0x12a2bbfff?, {0x102cc30e3?, 0x14000066da8?}, {{0x102cc30e3?, 0x12a3f2e40?}, 0x1?, 0x14000112780?}, 0x8?)
	/Users/josh/go/pkg/mod/github.com/thomaspoignant/go-feature-flag@v0.28.0/variation.go:217 +0x40
github.com/thomaspoignant/go-feature-flag.(*GoFeatureFlag).BoolVariation(0x14000159f28?, {0x102cc30e3, 0x4}, {{0x102cc30e3?, 0x0?}, 0xa0?, 0x14000112780?}, 0x44?)
	/Users/josh/go/pkg/mod/github.com/thomaspoignant/go-feature-flag@v0.28.0/variation.go:84 +0x48
github.com/thomaspoignant/go-feature-flag.BoolVariation(...)
	/Users/josh/go/pkg/mod/github.com/thomaspoignant/go-feature-flag@v0.28.0/variation.go:26
main.main()
	/var/folders/f4/dlqjqljs70dbl279lrbdcdjc0000gn/T/tmp.6GuEmS7X/main.go:11 +0x58
exit status 2
```

**Comment by thomaspoignant** [comment]
@joshm91 thanks for this super details issue 🙏 this is much appreciated.
I am sorry that this bug was introduced.

I have opened a PR #361 to fix the issue.
I will create a new version soon with the fix.

**Comment by thomaspoignant** [comment]
The fix is available in the version `v0.28.1`.

**Comment by joshm91** [comment]
Wow, thank you so much for the quick fix, and for this great library in general!

**Comment by thomaspoignant** [comment]
> Wow, thank you so much for the quick fix, and for this great library in general!

Thanks a lot for your feedback this is much appreciated.
