### ISSUE TITLE
(feature) OpenFeature providers that don't require the relay proxy.

### ISSUE THREAD

**Issue by jeacott1** [thomaspoignant/go-feature-flag#469]
### Requirements

Hi all, first of all this project looks very promising, thanks for the work so far!
I'm looking at the initial openfeature javascript sdk provider (https://github.com/open-feature/js-sdk-contrib/blob/main/libs/providers/go-feature-flag) and wondering why it was implemented using the relay proxy when one of the big selling points of go-feature-flag is the ability to host a static file to drive config? Is there something in the spec preventing the provider from loading the config file on init/periodically and using it, or was it just the first stab at a provider impl?

For my case, I'd like to see a provider that loads and caches a config file from a configurable url on init and a configurable cache timeout so that it optionally uses that file until the page is refreshed. This way I have the option to generate new files for every config update (think  webpack file+.md5# filenames) and get a clean cache-avoid with http get requests  - no cache-control headers or other config required.

I don't see anything like this on the roadmap, would be good if it was I think.

Cheers.

**Comment by thomaspoignant** [comment]
Hello @jeacott1,
This is a good question and this is something I have thought about intensively before building the **relay-proxy**.

There is nothing in Open Feature forcing me to have the relay proxy, the reason why I decided to use the API approach was to speed up the languages coverage support, if I did not have added the relay proxy I would have to rebuild the GO Feature Flag library from scratch for every language which makes it harder to maintain and evolve in the long run.

Today we have 5 different providers available for Open Feature (JS/TS, java, go, .Net, python), and all of them are using the relay proxy.
But the GO provider can also support using the go module directly and not calling any external API (see https://github.com/open-feature/go-sdk-contrib/tree/main/providers/go-feature-flag#using-the-go-module-standalone-version).

I will happy to support exactly what you say but I see some tradeoffs that we should take into consideration:
- Being sure that the hashing method of the flag put the same user in the same bucket in all languages.
- Being sure that we develop the new features for each language at the same time.
- Being sure that the rules are evaluated the same way in all languages.

I guess for the frontend SDK this can make sense (for now the JS/TS provider is mostly here for backend), but maybe it will make sense in the long run to thing about it.

Considering all of this, I am happy to have your feedback about the decision made in the past.

**Comment by jeacott1** [comment]
@thomaspoignant thanks for your response!
For me, I'm not using 'go' anywhere. My projects are generally a mix of spring boot/legacy j2ee/.net, and ts/js/react, and the 'Open Feature' thing is very appealing to me. I didn't realise the logic was also buried in the relay, I can certainly see that maintaining multiple Open Feature providers would be work, but I can also see that every flag will require an api call. hopefully these are cached clientside for a period. It's a tricky problem for a small open source project. transpiling core logic libs from some primary source to the target langs might be an option (LLVM, gopherjs etc), but its probably more pain than its worth.

**Comment by thomaspoignant** [comment]
Hey @jeacott1 sorry for the late reply.
You got it, I don’t have the ressources myself to implement all the business logic in each providers.

I will close this issue, but I keep in mind your question and reconsider it for the future direction of the project.

**Comment by jeacott1** [comment]
@thomaspoignant thanks - I dont think I can use this project in that case. I cant see how performance or scale can be managed with every flag making calls to the server.

**Comment by thomaspoignant** [comment]
I am sorry to hear that, the caching part in the providers is also something I have under my radar, it will be implemented soon for simple flags (without complex rollout).

So keep looking for updates and I hope it will solve what you don’t like in actual version of GO Feature Flag.

In any case, if you want to make the project better you are welcome to contribute too.

**Comment by jeacott1** [comment]
@thomaspoignant how would I use the GO version in react and java apps?

**Comment by thomaspoignant** [comment]
@jeacott1 still with the relay proxy but i will add an extra cache layer in the provider to avoid having to call the API each time you evaluate a flag.

**Comment by jeacott1** [comment]
@thomaspoignant ok.
an alternative you might not have considered would be to create a webassembly from your go engine and call it from your js provider. that would get you browser support. java support exists but via jni which isnt nice.
I guess a more work and initially probably less appealing option might be to rewrite the engine in js/ts and use it everywhere. most languages have support to run javascript libs.
