### ISSUE TITLE
(bug) Relay proxy returns 'Version' field as string while Open Feature provider expects int

### ISSUE THREAD

**Issue by lucashuang97** [thomaspoignant/go-feature-flag#488]
### Observed behavior

I'm trying to use the relay proxy with the OpenFeature Go-Feature-Flag sdk, and I'm running into the same error on every flag evaluation:

` openfeature: TYPE_MISMATCH: unexpected type for flag <flag-name>`

Relay proxy logs show a correct result being sent as a response so I took a look at the OpenFeature provider.

Digging into the code I see the error is actually a JSON Unmarshal error where it tries to unmarshal the response Version field (string) into the model EvalResponse's Version field (int). https://github.com/open-feature/go-sdk-contrib/blob/35f39f8f002006cc35c3620f3c33d6f96ebfab42/providers/go-feature-flag/pkg/provider.go#L302

 [What we expect to receive from the relay](https://github.com/open-feature/go-sdk-contrib/blob/35f39f8f002006cc35c3620f3c33d6f96ebfab42/providers/go-feature-flag/pkg/model/eval_response.go#L7)
[What is sent by the relay ](https://github.com/thomaspoignant/go-feature-flag/blob/1ea7f39c4f1e780decf557998b2e8721008aa4d7/internal/model/variation_result.go#L9)

### Expected Behavior

I expect the output of the relay proxy to be in the correctly read by the OpenFeature go-feature-flag provider.

### Steps to reproduce

Any simple example involving the relay proxy and the OpenFeature go-feature-flag provider seems to fail due to the type mismatch.

**Comment by thomaspoignant** [comment]
Hello @lucashuang97, 
Good catch, this bug appeared with the `v1.0.0` of GO Feature Flag.
You can roll back your **relay-proxy** to version `v0.3` and it will unblock you.

For the `v1.0.0` compatibility, I have opened this PR https://github.com/open-feature/go-sdk-contrib/pull/102 that will fix the issue. As soon as it is merged you will be able to use the latest version of the relay-proxy.

**Comment by thomaspoignant** [comment]
@lucashuang97 this issue was closed because the PR has been merged to `main`, but you will be able to use the new provider version in `0.1.3` only when this PR https://github.com/open-feature/go-sdk-contrib/pull/104 will be merged.

**Comment by thomaspoignant** [comment]
@lucashuang97 the release of the provider has been done.
You can use version `0.1.3` of the provider to be compatible with the **relay proxy** `v1.0.0`.

https://github.com/open-feature/go-sdk-contrib/releases/tag/providers%2Fgo-feature-flag%2Fv0.1.3
