### ISSUE TITLE
(feature) Relay proxy add GRPC/protobuf support

### ISSUE THREAD

**Issue by thomaspoignant** [thomaspoignant/go-feature-flag#503]
# Problem
The relay proxy currently only supports HTTP, which may not be the most efficient way to communicate in all cases. There is a need to support GRPC/protobuf for more efficient communication.

# Proposal
The proposal is to add support for GRPC/protobuf to the relay proxy. To do this, we can use the Echo HTTP framework, as it can be supercharged with protobuf to enable efficient communication.

# Requirements
The feature should meet the following requirements:
- The relay proxy should be modified to support GRPC/protobuf communication in addition to HTTP.
- The Echo HTTP framework should be used to implement the GRPC/protobuf communication.
- The feature should not significantly impact the performance of the relay proxy.

# Implementation
To implement this feature, we can follow the steps outlined in the following article: https://medium.com/swlh/supercharge-your-rest-apis-with-protobuf-b38d3d7a28d3

**Comment by sarvsav** [comment]
Hello @thomaspoignant May I request you to assign this task to me? It will give me good opportunity to learn this topic.

**Comment by thomaspoignant** [comment]
Hey @sarvsav sure I'll affect it to you!
I am looking forward to your PR. Take your time and let me know if you need any help with it.

**Comment by thomaspoignant** [comment]
@tach200 sorry for the broken link, I fixed it.
https://medium.com/swlh/supercharge-your-rest-apis-with-protobuf-b38d3d7a28d3

**Comment by thomaspoignant** [comment]
**GO Feature Flag** will implement the `OpenFeature Remote Evaluation Protocol` that is currently in definition mode.
There is a high chance that it will override this need, so I will close this stale issue and we will reopen one when the OREP is define.
