### ISSUE TITLE
Push go-feature-flag relay proxy to homebrew

### ISSUE THREAD

**Issue by thomaspoignant** [thomaspoignant/go-feature-flag#510]
# Description

Today you can install the **relay proxy** using brew but you have to install first a **tap**.
It would be nice to be able to install the `go-feature-flag-relay-proxy` directly from Homebrew.

We should also take care to update the version when releasing a new version.

This article explains how it was made for `flagd`: https://medium.com/@colellajosemiguel/flagd-formula-my-first-contribution-to-the-homebrew-project-ab33dba470e8
Actual brew file in the custom repo: https://github.com/thomaspoignant/homebrew-tap/blob/master/go-feature-flag-relay-proxy.rb

**Comment by dhanusaputra** [comment]
hi, can I try help with this please, thanks
