### ISSUE TITLE
(feature) Configuration linter

### ISSUE THREAD

**Issue by garriguv** [thomaspoignant/go-feature-flag#511]
### Requirements

Hi,

I'd like to add a new command to lint flag files, which could be used in CI systems to ensure that changes made to configuration files can be parsed by go-feature-flag.

Is this something that's been considered before? I searched for "lint", "linter" but didn't find anything relevant.

Here's how I think it could work:

    go-feature-flag-lint --flags-file <path to flags file>

The exit code would be non 0 if there are errors:
* non-valid json, toml, or yaml
* query formatting errors
* etc…

What do you think?

**Comment by thomaspoignant** [comment]
Hey @garriguv, this is something I had in the back of my head but never prioritized it, that is why I don't have an issue open yet.

If you want to work on this it would be super nice.
Let me know if you need any input on how to start this, but I will encourage you to start your new command line in the [`cmd`](https://github.com/thomaspoignant/go-feature-flag/tree/main/cmd) folder.
