### ISSUE TITLE
(feature) Support for metrics using Prometheus in relay proxy 

### ISSUE THREAD

**Issue by Rongtao-Fu-Imprivata** [thomaspoignant/go-feature-flag#529]
### Requirements

To use Go Feature Flag in relay proxy mode in  production, it's important to support metrics by using Prometheus. So it can monitored like other services. We are comparing open source feature flag systems that supports OpenFeture, including Flagd and Go Feature Flag. This is an area that Go Feature Flag can be improved compared to flagd which supports native metrics by using Prometheus.

**Comment by thomaspoignant** [comment]
Hello @Rongtao-Fu-Imprivata, this is actually a super nice idea and we should consider this for sure.
I think this is definitely a good way to improve the `relay-proxy`.

Let me try to find time to work on this in the near future.

**Comment by thomaspoignant** [comment]
Also @Rongtao-Fu-Imprivata I would be interested to know which metrics you would be interested in.
Are API calls enough or do you want more than that, such as a refresh of the configs etc ... ?

**Comment by Rongtao-Fu-Imprivata** [comment]
Evaluation API call metrics like response time, size in bytes, success/failure rate are super helpful to monitor the service performance, throughput, reliability. Other interesting metrics can be number of evaluation rules, how often those rules are added/removed/updated, response time, success/failure rate to retrieve evaluation rules from an external storage, which can be helpful for evaluation rule management.

**Comment by thomaspoignant** [comment]
@Rongtao-Fu-Imprivata I have opened this pull request #555 that is providing a `/metrics` endpoint that is exposing the prometheus metrics.

Can you have a look at the pull request and tell me if it is aligned with what you had in mind?
