### ISSUE TITLE
(bug) The latest version of java OpenFeature provider doesn't support relay proxy version v1.3.0+

### ISSUE THREAD

**Issue by Yaroslav-Kovalchyk-Imprivata** [thomaspoignant/go-feature-flag#582]
### Observed behavior

dev.openfeature.contrib.providers.gofeatureflag.GoFeatureFlagProvider fails to parse "cacheable" attribute of relay proxy response. This flag is added in v1.3.0 into VariationResult structure.
Used SDK and providers versions:
 'dev.openfeature:sdk:1.3.0'
 'dev.openfeature.contrib.providers:go-feature-flag:0.2.3'

### Expected Behavior

New providers version that is able to parse the latest relay proxy response is available.

**Comment by toddbaert** [comment]
@thomaspoignant is this something that needs to be implemented in the GoFF provider in [contribs](https://github.com/open-feature/java-sdk-contrib)?

**Comment by toddbaert** [comment]
@thomaspoignant merged and released. The new version should be available on maven central in 1h or so.

**Comment by Yaroslav-Kovalchyk-Imprivata** [comment]
Thank you, @thomaspoignant, for a quick fix!
