### ISSUE TITLE
(bug) config file for basic demo ?

### ISSUE THREAD

**Issue by gedw99** [thomaspoignant/go-feature-flag#634]
### Observed behavior

no config in https://github.com/thomaspoignant/go-feature-flag/tree/main/examples/demo

flags.yaml.

### Expected Behavior

a config.

**Comment by thomaspoignant** [comment]
Good catch @gedw99, let me add one to make the demo usable.

**Comment by thomaspoignant** [comment]
@gedw99 I have merge to `main` branch the fix.
It should be now possible to use the demo with the right configuration file.

**Comment by gedw99** [comment]
thanks @thomaspoignant
