### ISSUE TITLE
(feature) Create helm documentation with readme-generator-for-helm

### ISSUE THREAD

**Issue by thomaspoignant** [thomaspoignant/go-feature-flag#664]
### Requirements
Create the helm documentation of the relay proxy using https://github.com/bitnami-labs/readme-generator-for-helm.

The helm chart is located in `cmd/relayproxy/helm-charts/relay-proxy`.
We should have a new command `make generate-helm-doc` in the makefile to create the helm documentation.

**Comment by sarvsav** [comment]
Hello @thomaspoignant, May I consider using this tool github.com/norwoodj/helm-docs/cmd/helm-docs@latest for the task? As it maintains the uniformity in the Makefile of using GO tools. :)

**Comment by thomaspoignant** [comment]
Hello @sarvsav I was not aware of this tool but it looks good too.
You can use it for sure.
