### ISSUE TITLE
(documentation) Adding better documentation on what is the relay proxy

### ISSUE THREAD

**Issue by thomaspoignant** [thomaspoignant/go-feature-flag#753]
## Requirement
For now, in the documentation, we don't really explain well what is the relay proxy and how it works.

It will be great to have a page explaining exactly what is the relay proxy and what problem it solves.

**Comment by thomaspoignant** [comment]
I like the name GO Feature Flag Server, let me think how we can rename this in the future without breaking everything and keeping consistency.

But good catch about the naming.

**Comment by yangzhaox** [comment]
Further more, in order to reach a larger number of users beyond Go community, I feel the relay proxy (or GOFF server) should be the first-class citizen and put into a more prominent position in README.md and documentation.

**Comment by thomaspoignant** [comment]
I actually agree with that the relay-proxy/server/??? is more and more the central point of the project.
I may need to rework the doc to make this explicit, If you have idea how to present this I would be super interested.
