### ISSUE TITLE
(feature) Folder retriever for large development organization

### ISSUE THREAD

**Issue by yangzhaox** [thomaspoignant/go-feature-flag#799]
### Requirements

Imagine a large dev org having hundreds of dev teams, each team wants to define their own feature flags and they do not want to interfere each other. So instead of relying on a single file for feature flag definition, a folder (potentially with sub-folders) can be leveraged to contain all the feature flag files. Each team gets a dedicated folder for their feature flag files and we can even leverage **CODEOWNERS** file to define ownership.

**Comment by thomaspoignant** [comment]
@yangzhaox thanks for this idea, actually you can already provide multiple files using multiple retrievers.
You can check the doc about that here https://gofeatureflag.org/docs/configure_flag/store_your_flags#use-multiple-configuration-flag-files

Having a folder is a good idea, but I am struggling to understand how you see this.
I can see how to do that with a file retriever, but do you expect it to work with Github, Gitlab, etc ... retrievers too?

For me, the main challenge here will be how to deal if multiple files defining the same flag name, which one should be the source of truth?

Let's say we have something like that:
```
flags_dir/
 ├── flag-team-a.yaml   ..................... define flag for team A (contains a flag named `flag-test`)
 ├── flag-team-c.yaml   ..................... define flag for team B (contains a flag named `flag-test`) 
 ├── flag-team-b.yaml   ..................... define flag for team C
 └── flag-team-d.yaml   ..................... define flag for team D (contains a flag named `flag-test`)
```

Which one should we use and when?

**Comment by yangzhaox** [comment]
@thomaspoignant what I envisioned is like this:
```
flags_dir/
 ├── team_a_dir/
 |    ├── CODEROWNERS
 |    ├── flag-1.yaml
 |    ├── flag-2.yaml
 ├── team_b_dir/
 ├── team_c_dir/
 └── team_d_dir/
```
The folder **flags_dir** will be part of a git repo where all teams should have their own dedicated sub-folder and flag yaml files. Every time a team commits a new flag yaml file, there will be a pipeline running to check / validate these yaml files and make sure they are valid GOFF rules and do not have the same flag defined in multiple teams. Finally this folder and its content will be mounted as volume to the pod/container where GOFF relay proxy is running so our new **folder retriever** will load all the yaml files underneath. If there is any invalid yaml file, GOFF will skip it and continue to load the others so one team's mistake won't affect the flags of other teams. And I don't think we need to support this in other existing retrievers like github, gitlab, s3, etc.

**Comment by thomaspoignant** [comment]
I like the approach but it requires some tooling to manage the repositories itself and this can go beyond the scope of the project.

Or we should evolve the linter to be able to scan a folder of files.

**Comment by yangzhaox** [comment]
yes this idea might be a better fit for custom retriever who has multiple teams in a large dev org. And I like the idea of allowing the linter to be able to scan a folder of files.
