### ISSUE TITLE
(feature) doc create a all docs version page

### ISSUE THREAD

**Issue by thomaspoignant** [thomaspoignant/go-feature-flag#830]
### Requirements

Currently, we are not displaying all versions available of the doc in the drop-down list
![Screenshot 2023-05-26 at 14 55 30](https://github.com/thomaspoignant/go-feature-flag/assets/17908063/6f19e85c-b667-45de-91b7-d622c22a2c39)

It will be great to have a link to go to a page to see all the versions.
Similar to what we can see in https://relay.dev/versions/.
![Screenshot 2023-05-26 at 14 54 31](https://github.com/thomaspoignant/go-feature-flag/assets/17908063/d1863e06-128b-431d-968b-e4b2a3fa0e0c)

**Comment by achhayapathak** [comment]
so you basically want an all-versions option at the end of the drop-down and then a separate page for versions that contains all the links?

**Comment by thomaspoignant** [comment]
> yeah but i don't have any experience with go language
This page is not build in GO but with react using docusaurus.
