### ISSUE TITLE
(feature) A mechanism for blocking on the initial flag load

### ISSUE THREAD

**Issue by jamesmulcahy** [thomaspoignant/go-feature-flag#858]
### Requirements

I've integrated this library into an application of mine, and in writing unit tests, I'm hitting race conditions against the async load of the flags into the cache.  I don't see an API/mechanism for blocking on the initial load of the flag data.

I'm curious how people are handling this today -- am I overlooking something, or is this a feature you'd be open to including?

**Comment by thomaspoignant** [comment]
Hey @jamesmulcahy thanks for opening this issue.
Can you provide a more detailed description of the problem you're facing? It would be awesome if you could explain in detail what you've discovered.

Do you have some code examples that I can use to reproduce it?

What you are looking for is a way to wait that the initial loading to be complete before being able to evaluate the flag?

**Comment by jamesmulcahy** [comment]
> What you are looking for is a way to wait that the initial loading to be complete before being able to evaluate the flag?

Yes, exactly right.

The issue right now is that if I write a test which depends on feature flag configuration, the execution of the test races against the background loading of the feature flag configuration.  This leads to the test failing sporadically.

The workaround I'm using for now is to add this at the top of tests which I know are loading flags:

```
func WaitForInit(t *testing.T) {
	require.Eventually(t, func() bool {
		flags, err := ffclient.GetFlagsFromCache()
		return err == nil && len(flags) > 0
	}, 1*time.Second, 50*time.Millisecond)
}
```

But I'd prefer a more generic approach, for example, if there was a `ffclient.GetInitializationChan()` which returned a channel which was closed once the initial flag load was complete.  That way, I could write something like this:

```
ffclient.Init(...)

<-ffclient.GetInitializationChan()
```

Or if people wanted something more advanced/robust, they could add a timeout...


```
ffclient.Init(...)

select {
  case <-ffclient.GetInitializationChan()
    // Success!
  case <-time.Tick(1 * time.Second)
    // Timeout, failure...
}
```

I'd be happy to put together a PR along these lines (or another approach, if you have another idea/preference)

**Comment by thomaspoignant** [comment]
@jamesmulcahy I was reading the code again and I am not sure to understand why you have this problem.
The `Init` function is doing the first load of the flag in a synchronous way in the same thread as the init function.

The thread is following these steps:
```
Init()
  --> New()
    --> retrieveFlagsAndUpdateCache(goFF.config, goFF.cache)
      --> goFF.startFlagUpdaterDaemon() //We launch the daemon to update the flag in the background 
```
You can check the initial load [here](https://github.com/thomaspoignant/go-feature-flag/blob/220198af359604f41acccf0d27f6c57b63fd8b7e/feature_flag.go#L87).

It means that after your call of the `Init` function,  the loading of the flags should is supposed to be already ok.
If you occur race conditions maybe something is not working as expected.

Do you have an example of a test to help me to reproduce the issue?

**Comment by jamesmulcahy** [comment]
Interesting point, thanks for taking a look so closely.  Having looked again myself, I think the problem is here:

```
for index, r := range retrievers {
		// Launching GO routines to retrieve all files in parallel.
		go func(r retriever.Retriever, format string, index int, ctx context.Context) {
			defer wg.Done()
			rawValue, err := r.Retrieve(ctx)
			if err != nil {
				resultsChan <- Results{Error: err, Value: nil, Index: index}
				return
			}
			convertedFlag, err := cache.ConvertToFlagStruct(rawValue, format)
			resultsChan <- Results{Error: err, Value: convertedFlag, Index: index}
		}(r, config.FileFormat, index, config.Context)
	}

	retrieversResults := make([]map[string]dto.DTO, len(retrievers))
	for v := range resultsChan {
		if v.Error != nil {
			return v.Error
		}
		retrieversResults[v.Index] = v.Value
	}
```

The first range launches a set of goroutines which will eventually write into `resultsChan`.  But the code will immediately fall through and execute the next for loop, which iterates over `range resultsChan`.  There's nothing to guarantee that anything has been written to `resultsChan` at this point, and I suspect the for loop completes without any of the retreivers having run, and written their result into `resultsChan`.  As a result, I have to wait for the next background cache load to complete, before the flags are available to me.

I don't have an independent test that reproduces this (it's heavily coupled with some internal/private source code), but let me see if I can put one together.

**Comment by thomaspoignant** [comment]
@jamesmulcahy were you able to reproduce?
If so I will be interested to dig more in detail on the problem.
