### ISSUE TITLE
(feature) Add a kafka data exporter

### ISSUE THREAD

**Issue by thomaspoignant** [thomaspoignant/go-feature-flag#89]
# Requirements
Add a kafka data exporter but this time since we are using an async system we should produce an event everytime someone is calling a variation.

**Comment by MattSilvaa** [comment]
Hello!

Do you still need help with this?

**Comment by thomaspoignant** [comment]
Hello @MattSilvaa,
I did not start anything around that, so if you want to help it would be awesome.

**Comment by davidaparicio** [comment]
Hello Thomas!

Is this feature still needed ?

Kind regards,
David

**Comment by thomaspoignant** [comment]
Hey @davidaparicio yes this feature is still needed.
Would you be interested to implement it?

**Comment by davidaparicio** [comment]
Yes, why not to try to implement it ;)
