### ISSUE TITLE
(Feature) Package go-feature-flag in an API to use it with different language

### ISSUE THREAD

**Issue by thomaspoignant** [thomaspoignant/go-feature-flag#96]
# Requirements
Package `go-feature-flag` with an API on top to make it usable for other languages.

- Create an API on top of the SDK.
- A docker package should also be available to use as a sidecar container.
- It should probably be in another repository.

**Comment by cobraz** [comment]
What about RPC? 🤷‍♂️

RPC can be used both locally and over a network, maybe that makes sense?

**Comment by thomaspoignant** [comment]
For information I am working on a new repository called go-feature-flag relay proxy that will expose `go-feature-flag` with a rest API.

There is also a plan to extent it with GRPC support.

As soon as the repository is ready I will link this new software here.
