### ISSUE TITLE
(feature) Adding event source field

### ISSUE THREAD

**Issue by liran2000** [thomaspoignant/go-feature-flag#978]
### Introduction
Evaluation event is used for statistics purposes.  
The event can be published by the proxy, or from the [provider](https://github.com/open-feature/java-sdk-contrib/pull/369).

### Feature
Enrich event by adding it _source_ field which represents the source which publishing the message:
- PROXY: set by the proxy when evaluated
- PROVIDER_CACHE: set by the provider when evaluated from cache

### Tasks
- server-side: Support it at server-side for receiving the optional field and enrich the statistics by it.
- Proxy: set PROXY source by the proxy when evaluated
- OpenFeature Providers: set PROVIDER_CACHE source by the provider when evaluated from cache.
  This is for providers which implemented cache, currently GO and Java.

**Comment by thomaspoignant** [comment]
That's a good idea to add the source of the event in the format [`FeatureEvent`](https://github.com/thomaspoignant/go-feature-flag/blob/98c7b28cfeb451a5857bf03913b522eead749c6c/exporter/feature_event.go#L37) and fill it when creating a feature event.

But I would prefer to go with this name:
- `SERVER` set when evaluated in the relay-proxy
- `PROVIDER_CACHE`: set by the provider when evaluated from the cache.

**Comment by andrebenedetti** [comment]
Hello! Saw this marked as a good first issue and I’d like to give it a try :)

**Comment by thomaspoignant** [comment]
Hey @andrebenedetti, this is all yours!
I'll assign it to you so you are sure that no one is working on it at the same time.

If you need any tips or info please let me know.

**Comment by andrebenedetti** [comment]
Took some time to get familiarized with the repository (which is awesome, by the way!) and started some work here https://github.com/thomaspoignant/go-feature-flag/compare/main...andrebenedetti:go-feature-flag:feature/add-event-source-field, in case you want to take a look. Will continue tomorrow after work 

 This is the first Go project I work on, so I'm trying to figure out why my formatter wants to reorder imports differently than what's in the repo :thinking: any clues? Sorry for such a basic question :laughing:

**Comment by thomaspoignant** [comment]
Hey @andrebenedetti which IDE are you using? I am using IntelliJ so maybe it has a different policy.
Anyway don't block your self for this, this is not super important 😉
